### ISSUE TITLE
async naming

### ISSUE THREAD

**Issue by wtgee** [tyarkoni/transitions#101]
I've been using and testing out the `async` feature for queued processing and all seems to be working well however I find myself wondering at the name `async`. Wouldn't it make more sense to have the named parameter be `queued` or something? 

Not a big deal, but this feature doesn't really have anything to do with the `async` module and I think it might lead to some confusion for people who are trying to use some of python's new `async` features.

Thoughts? (Also, sorry for not catching this before it went into master but I don't think we've done an actual release yet...)

**Comment by aleneum** [comment]
Yeah, I agree. 'async' might confuse people. I sticked to it since it was the chosen term to discuss this feature with @khigia. 'queued' sounds good to me but might also be too generic. I was wondering if 'queued_transition' or -- the opposite -- 'immediate_transition' would be more self-explanatory.

**Comment by aleneum** [comment]
@wtgee: Do you have any further suggestions? Do you prefer queued or queued_transitions? Or maybe transition_strategy='queued' (default would be 'instant') :P?

**Comment by wtgee** [comment]
I would say that since the module itself is 'transitions' we can make the
linguistic assumption and just go with `queued` :) However, if we think
there will be more than the two options then maybe the
`transition_strategy` is best.  I vote for just `queued` though, with
`queued=False` as the default.

No strong feelings though.

**Comment by tyarkoni** [comment]
+1 to @wtgee. I liked queued; it's fairly easy to infer what it means. For transition_strategy, you almost certainly need to read the docs.

**Comment by wtgee** [comment]
I'll fix this up after this weekend when I will have a bunch more time.

**Comment by wtgee** [comment]
I made this change. It made more sense to me to have `has_queue` than to say `queued` to test the machine. We could add both but it's stored as `_queued` right now.

**Comment by aleneum** [comment]
`has_queue` is very good change in my opinion 👍. looking forward to the merge
