### ISSUE TITLE
Minor problem with setting diagram title

### ISSUE THREAD

**Issue by andrewramsay** [tyarkoni/transitions#102]
I wanted to define a state machine so I could generate a diagram using the extensions. It worked as expected except that the title I set when creating the GraphMachine was ignored (the diagram just showed "AGraph" in place of the title I wanted). 

I had followed the quickstart example structure in defining my machine, and from looking through the code I think the problem is that the GraphMachine.add_transition method does this:
`self.graph = self.get_graph(force_new=True)`
which causes the get_graph function to default back to the class name as the title.

If instead it passed in the Machine title:
`self.graph = self.get_graph(title=self.title, force_new=True)`
then I think that would make more sense as you wouldn't expect to lose the title by adding a transition.

**Comment by aleneum** [comment]
Hi @andrewramsay,

the machine's title had not been passed correctly to `get_graph`. This should be fixed now. If the problem still occurs feel free to reopen the issue. Thanks for the report!

Best regards,
Alex
