### ISSUE TITLE
Error 0777

### ISSUE THREAD

**Issue by rolandettema** [tyarkoni/transitions#103]
Installing GraphMachine does not work in Python 3.4 I receive an error 

[Anaconda3] C:\Users\RET>pip install -U graphmachine
Collecting graphmachine
  Using cached graphmachine-3.0.0.48.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RET\AppData\Local\Temp\pip-build-wrsggrp6\graphmachine\setup.py", line 33
        mode = 0777
                  ^
    SyntaxError: invalid token

**Comment by tyarkoni** [comment]
I think you're confusing the GraphMachine class in Transitions with a separate package in PyPI. If you want to use the Transitions GraphMachine, just `import GraphMachine from transitions.extensions`. If you want to use the GraphMachine package available on PyPI,  you'll need to look for support elsewhere, as we have no relation to that package.

**Comment by rolandettema** [comment]
Thanks,

I want to run the examples in transitions, it gives an error.

Exception                                 Traceback (most recent call last)
<ipython-input-2-4eeafb792d7c> in <module>()
     13                          auto_transitions=False,
     14                          initial='standing',
---> 15                          title="Mood Matrix")
     16 machine.show_graph()


Cheers Roland Ettema

Van: Tal Yarkoni [mailto:notifications@github.com]
Verzonden: donderdag 19 mei 2016 14:33
Aan: tyarkoni/transitions
CC: Ettema, Roland; Author
Onderwerp: Re: [tyarkoni/transitions] Error 0777 (#103)


I think you're confusing the GraphMachine class in Transitions with a separate package in PyPI. If you want to use the Transitions GraphMachine, just import GraphMachine from transitions.extensions. If you want to use the GraphMachine package available on PyPI, you'll need to look for support elsewhere, as we have no relation to that package.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/tyarkoni/transitions/issues/103#issuecomment-220310609>

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

**Comment by aleneum** [comment]
Hi @rolandettema,

did you use PyPI to install transitions? The notebook examples require version 0.4.0 which is not available through PyPI yet. If you want to test the 0.4.0 features right away you need to clone and build transitions from github.

Best regards, 
Alex

**Comment by rolandettema** [comment]
Hi Alex,

ok I will try to follow your suggestions but what I see until know is that I battle dependency with

build\lib.win-amd64-3.5\pygraphviz


Met vriendelijke groet / With kind regards,

Roland Ettema
Bestuursdienst Open Universiteit
Valkenburgerweg 177
6419 AT Heerlen
The Netherlands

T: +31 (0) 45-576 2502
M: +31 (0) 6 15866614
E: roland.ettema@ou.nl
www.ou.nl
________________________________________

**Comment by aleneum** [comment]
I see,

have you tried to install pygraphviz via pip as suggested in the ReadMe?

> Transitions can generate basic state diagrams displaying all valid transitions between states. To use the graphing functionality, you'll need to have pygraphviz installed (pip install pygraphviz)

**Comment by rolandettema** [comment]
Yes I did, but pygraphviz wants to use a C++ compiler of Microsoft Visual Studio. He cannot find vcvarsall.bat

logging:


[Anaconda3] C:\Users\RET>pip install pygraphviz
Collecting pygraphviz
  Using cached pygraphviz-1.3.1.zip
Building wheels for collected packages: pygraphviz
  Running setup.py bdist_wheel for pygraphviz ... error
  Complete output from command d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\RET\\AppData\\Local\\Temp\\pip-build-vjdb2mku\\py
graphviz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\RET\AppData
\Local\Temp\tmpsyh341p7pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\agraph.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\release.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\version.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\__init__.py -> build\lib.win-amd64-3.5\pygraphviz
  creating build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  running egg_info
  writing top-level names to pygraphviz.egg-info\top_level.txt
  writing pygraphviz.egg-info\PKG-INFO
  writing dependency_links to pygraphviz.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc\build'
  writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
  copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.5\pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  error: Unable to find vcvarsall.bat




Met vriendelijke groet / With kind regards,

Roland Ettema
Bestuursdienst Open Universiteit
Valkenburgerweg 177
6419 AT Heerlen
The Netherlands

T: +31 (0) 45-576 2502
M: +31 (0) 6 15866614
E: roland.ettema@ou.nl
www.ou.nl
________________________________________

**Comment by aleneum** [comment]
I cannot help you with that, sorry. But it seems like you are not the only one having issues installing pygraphviz on Windows. You lack the required build tools. Have a look at [Stackoverflow](http://stackoverflow.com/a/28832992/1617563) or [MSDN](https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/). MiniGW is an option. Or just google `pygraphviz error: Unable to find vcvarsall.bat`. I found many approaches (which I cannot test though).

**Comment by rolandettema** [comment]
It is undoable to get pygraphviz installed, very pitty that i cannot graphically support transitions in a working example

This site helped me a lot https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/
However, I got stuk on not finding graphviz/cgraph.h
'
graphviz.org was unreachable

Met vriendelijke groet / With kind regards,

Roland Ettema
Bestuursdienst Open Universiteit
Valkenburgerweg 177
6419 AT Heerlen
The Netherlands

T: +31 (0) 45-576 2502
M: +31 (0) 6 15866614
E: roland.ettema@ou.nl
www.ou.nl
________________________________________

**Comment by rolandettema** [comment]
Alexander,

I cannot work with the graphmachine it is a library thing. This is a pitty.

However I like the statemachine software a lot!

I use it in a simulation of a business transaction. What I like to achieve is stochastic behavior between the state changes. For example a state change from A to B occurs
randomly and normally distributed.

Is this a randomly normally distributed state change in your interest?

Regards

Roland


-----Oorspronkelijk bericht-----
Van: Ettema, Roland
Verzonden: donderdag 19 mei 2016 20:38
Aan: tyarkoni/transitions; tyarkoni/transitions
CC: Mention
Onderwerp: RE: [tyarkoni/transitions] Error 0777 (#103)

Yes I did, but pygraphviz wants to use a C++ compiler of Microsoft Visual Studio. He cannot find vcvarsall.bat

logging:


[Anaconda3] C:\Users\RET>pip install pygraphviz Collecting pygraphviz
  Using cached pygraphviz-1.3.1.zip
Building wheels for collected packages: pygraphviz
  Running setup.py bdist_wheel for pygraphviz ... error
  Complete output from command d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\RET\\AppData\\Local\\Temp\\pip-build-vjdb2mku\\py
graphviz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\RET\AppData
\Local\Temp\tmpsyh341p7pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\agraph.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\release.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\version.py -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\__init__.py -> build\lib.win-amd64-3.5\pygraphviz
  creating build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.5\pygraphviz\tests
  running egg_info
  writing top-level names to pygraphviz.egg-info\top_level.txt
  writing pygraphviz.egg-info\PKG-INFO
  writing dependency_links to pygraphviz.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc\build'
  writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
  copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.5\pygraphviz
  copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.5\pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  error: Unable to find vcvarsall.bat




Met vriendelijke groet / With kind regards,

Roland Ettema
Bestuursdienst Open Universiteit
Valkenburgerweg 177
6419 AT Heerlen
The Netherlands

T: +31 (0) 45-576 2502
M: +31 (0) 6 15866614
E: roland.ettema@ou.nl
www.ou.nl
________________________________________
