### ISSUE TITLE
Does it work with Django? failed to initialize machine for Django models

### ISSUE THREAD

**Issue by AlexPython** [tyarkoni/transitions#111]
Hi!
Thanks for a comprehensive readme, examples were really great!
I assumed it should work in a Django-based app as it is Python, so I `pip installed` transitions and wrote a simple model to play with.

And the app crashed failing to initialize the state machine.
I tried two ways:

1. Initialize in an existing models class's `def __init__` (dev server started OK, but querying model objects failed).
2. Initialize outside of class as described in the readme, but Django can't attach the states machine to the model.

## Here' my code

```
from django.db import models
from transitions import Machine

class Car(models.Model):
    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'), blank=True)
    color = models.CharField(_('color'), max_length=50)

    def __str__(self):
        return "%s %s" % (self.color, self.title)

    # states & transitions
    CAR_STATES = ['on_factory', 'in_showroom', 'sold']

    CAR_TRANSITIONS = [
        {'trigger': 'buy', 'source': 'on_factory', 'dest': 'in_showroom'},
        {'trigger': 'sell', 'source': 'in_showroom', 'dest': 'sold'},
    ]

    # NameError: name Car is not defined
    machine = Machine(model=Car, states=CAR_STATES, transitions=CAR_TRANSITIONS, initial='on_factory')
```

It gives me an error (Django 1.9.4):

```   
machine = Machine(model=Car, states=CAR_STATES, transitions=CAR_TRANSITIONS, initial='on_factory')
NameError: name 'Car' is not defined
```

Am I doing something wrong or is it not supposed to work in Django?

**Comment by wtgee** [comment]
Hi @AlexPython , glad you are giving it a try.

I'm not somewhere I can test this, but you'll want to create an instance of your `Car` object and pass that to the `model` param.  Something like:

```python
my_car = Car()
...
machine = Machine(model=my_car, ...)

```
If that is still giving you problems we can work through but give that a try.

**Comment by AlexPython** [comment]
I tried this, it does not work.
I also, moved the code to another file (so as to import the model) like this:

```
    from .models import Car
    car_model = Car()
    another_machine = Machine(model=car_model, states=CAR_STATES, transitions=CAR_TRANSITIONS, initial='on_factory')

```

Dev server starts, but in shell no object has states: default `Car` instances know nothing about states, and as for `car_model` instance referenced in the Machine, it does not exist in shell and can't be imported.

I copypasted the "batman" example and it works fine with a simple `class Anything (object)`.
As for Django models, they inherit from Django classes like `class Django (models.Model)` and some internal mechanics seem to prevent Django models from attaching states.

**Comment by aleneum** [comment]
Hi @AlexPython,

since I cannot test your setup, I had to stick with the [django tutorial](https://docs.djangoproject.com/en/1.9/intro/tutorial02/).

I set up an app as described there until `python manage.py shell` and tested the following:

```python
from polls.models import Question, Choice
from transitions import Machine
from django.utils import timezone

CAR_STATES = ['on_factory', 'in_showroom', 'sold']
CAR_TRANSITIONS = [
    {'trigger': 'buy', 'source': 'on_factory', 'dest': 'in_showroom'},
    {'trigger': 'sell', 'source': 'in_showroom', 'dest': 'sold'},
]
q = Question(question_text="What's new?", pub_date=timezone.now())
machine = Machine(model=q, states=CAR_STATES, transitions=CAR_TRANSITIONS, 
                  initial='on_factory')
hasattr(q, 'sell') # returns True
q.sell # returns <bound method Event.trigger of <transitions.core.Event ...>>
machine.current_state.name # returns 'on_factory'
q.buy() # returns True
machine.current_state.name # returns 'in_showroom'
```
This worked like a charm. I did not test how django specific model methods behave like `save`.
You might want to use a debugger  to find out why it does not work for you or give the django tutorial a try as well.

best regards,
alex

**Comment by aleneum** [comment]
To stick with the 'NarcolepticSuperhero' example, I adapted the `Question` to hold its own machine instance class like this:

```python
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    CAR_STATES = ['on_factory', 'in_showroom', 'sold']

    CAR_TRANSITIONS = [
        {'trigger': 'buy', 'source': 'on_factory', 'dest': 'in_showroom'},
        {'trigger': 'sell', 'source': 'in_showroom', 'dest': 'sold'},
    ]

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.machine = Machine(self, states=Question.CAR_STATES,
                               transitions=Question.CAR_TRANSITIONS,
                               initial=Question.CAR_STATES[0])
```

Usage in the interactive shell changes slightly:

```python
from polls.models import Question, Choice
from django.utils import timezone
q = Question(question_text="What's new?", pub_date=timezone.now())
 q.machine.current_state.name # returns u'on_factory'
```

**Comment by AlexPython** [comment]
Thanks for the update, it did work!
I have both good news and bad news from my experiments.

### Here's what works fine

To make it simple I created a new model "AnotherCar" so as not to mess with existing models, and initialized it in `def __init__`:

```
>>> from tools.models import AnotherCar
>>> cars = AnotherCar.objects.all()
>>> cars
[<AnotherCar: white Ford Explorer 2015>, <AnotherCar: blue Ford Focus 2016>]
>>> car = cars[0]
>>> car
<AnotherCar: white Ford Explorer 2015>
>>> car.machine.current_state.name
'on_factory'
>>> car.buy()
True
>>> car.machine.current_state.name
'in_showroom'

```

Besides  `[model].machine.current_state.name` syntax, the plain syntax described in the readme works too fine: 

```
>>> fiesta = AnotherCar(title="Fiesta 2015", color="red")
>>> fiesta.save()
>>> cars
[<AnotherCar: blue Ford Focus 2016>, <AnotherCar: white Ford Explorer 2015>, <An
otherCar: red Fiesta 2015>]
>>> fiesta.state
'on_factory'
>>> fiesta.buy()
True
>>> fiesta.sell()
True
>>> fiesta.state
'sold'
>>> fiesta.is_sold()
True
```

### What did not work

However, I can't see states as fields in the database.
And Django's filtering does not work, because state is rather a function, not a field:

```
>>> fiesta.state
'sold'
>>> fiesta.is_sold()
True
>>> sold_cars = AnotherCar.objects.all().filter(is_sold=True)
```

ends in error: 

```
 "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'is_sold' into field.
Choices are: color, id, title
```

Same applies to filtering like `state='sold'`, `is_sold()=True`, etc, which is not valid syntax, I understand.
Django does not filter on functions.
So, I can't think of a way to filter cars with "sold" state, for example, and show them in the template.

### I thought about a workaround with redundant fields

I could add a redundant physical field like `current_state = models.Charfield(max_length=50)` and save any current state in plain text with an `after transition` function.
This would be redundant, but all out-of-box Django filtering would work besides the transitions/states functionality.

### And the workaround failed

Since states are not stored in the database, but initialized in `def __init__` they're reset to defaults when any query made.

Above, I created an entry (fiesta car), updated the state to "sold" and saved it.

Any new query forgets about states:

```
>>> import django
>>> from tools.models import AnotherCar
>>> cars = AnotherCar.objects.all()
>>> for car in cars: print (car.title, car.state)
...
Ford Focus 2016 on_factory
Ford Explorer 2015 on_factory
Fiesta 2015 on_factory
>>>
```

### Questions

I am confused.
If purpose of states is to remember the state of each item and process it in code and output, so:

1. Why initialize machine in class's `def __init__` as it resets states?
2. What is the supposed way to actually save states (not in memory, but in DB)?

**Comment by aleneum** [comment]
Hi,

> Why initialize machine in class's def __init__ as it resets states?
I assume you cannot name a django field like transition model attribute. So your suggested workaround should be okay. If you want to initialize a model with the last state one could think of `Machine(self, states=States, transitions=Transitions, initial=self.current_state)`. `current_state` would be a field as mentioned in your workaround.

> What is the supposed way to actually save states (not in memory, but in DB)?
As a text field like color or description. current_state will be saved and during initialisation should be set according to the underlying db model. If you use `current_state` and call `save`, you should be able to filter like `AnotherCar.objects.all().filter(current_state='in_showroom')`. Attributes like `is_in_showroom` are not part of your db model and therefore cannot be queried. You can try to store the machine and/or model instance directly into your db but thats rather inconvenient.

I will close this issue because in my opinion this does not look like an issue of `transition` as a library but rather a matter of how to implement a certain solution. Please ask your usage related questions on [stackoverflow](www.stackoverflow.com) and tag them with `transitions` and `python` so users of `transitions` can help you to solve your problem.

Feel free to reopen the issue if you think the previously discussed things do relate to a bug or feature request which I have overlooked so far.

Best regards,
Alex

**Comment by AlexPython** [comment]
Thanks everyone for help!

In case anyone later will need a quick "how to", below is the final working solution:

**Transitions in a Django model.**

```
class AnotherCar(models.Model):
    title = models.CharField(_('title'), max_length=100)
    color = models.CharField(_('color'), max_length=50)
    state_field = models.CharField(_('state field'), max_length=50, default='on_factory', editable=False)

    CAR_STATES = ['on_factory', 'in_showroom', 'sold']

    CAR_TRANSITIONS = [
        {'trigger': 'buy', 'source': 'on_factory', 'dest': 'in_showroom', 'after': 'update_state_field'},
        {'trigger': 'sell', 'source': 'in_showroom', 'dest': 'sold', 'after': 'update_state_field'},
    ]

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.machine = Machine(self, states=AnotherCar.CAR_STATES,
                               transitions=AnotherCar.CAR_TRANSITIONS,
                               initial=self.state_field)

    def update_state_field(self):
        self.state_field = self.machine.current_state.name
        self.save()

    def __str__(self):
        return "%s %s" % (self.color, self.title)
```

**Comment by aleneum** [comment]
looks good 👍

**Comment by harshithjv** [comment]
@AlexPython

Though you gave answer five years ago its quite a savior to me. But there are some issues maybe because library got updated meanwhile.

**Code update:**


```
from django.db import models
from django.utils.translation import gettext as _

from transitions import Machine


class AnotherCar(models.Model):
    title = models.CharField(_('title'), max_length=100)
    color = models.CharField(_('color'), max_length=50)
    state_field = models.CharField(_('state field'), max_length=50, default='on_factory', editable=False)

    CAR_STATES = ['on_factory', 'in_showroom', 'sold']

    CAR_TRANSITIONS = [
        {'trigger': 'buy', 'source': 'on_factory', 'dest': 'in_showroom', 'after': 'update_state_field'},
        {'trigger': 'sell', 'source': 'in_showroom', 'dest': 'sold', 'after': 'update_state_field'},
    ]

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.machine = Machine(self, states=AnotherCar.CAR_STATES,
                               transitions=AnotherCar.CAR_TRANSITIONS,
                               initial=self.state_field,
                               model_attribute="state_field")

    def update_state_field(self):
        self.save()

    def __str__(self):
        return f"{self.color.title()} - {self.title} [{self.state_field.replace('_', ' ').title()}]"
```

_Corrections I did:_
* The import statements for quick reference.
* Set `model_attribute` param to Machine object to define custom state field name. (This is a huge savior for django model fields.)
* Removed the reference to `self.machine.current_state`. This gave error. Is `machine.current_state` deprecated feature?

**Comment by aleneum** [comment]
Hi @harshithjv,

thank you for the update! 

> This gave error. Is machine.current_state a deprecated attribute?

yes, it has been removed: https://github.com/pytransitions/transitions/issues/128
