### ISSUE TITLE
__init__ methods don't call super

### ISSUE THREAD

**Issue by jonathanunderwood** [tyarkoni/transitions#112]
I've been trying to use transitions in a project where I want classes to inherit from Machine (or one of the extended variants) as well as other objects, and unfortunately Machine doesn't play nice - it doesn't accept *args, **kwargs, and doesn't call `super().__init__(*args **kwargs)` (py3), or `super(Machine,self).__init__(*args, **kwargs)` (py2/py3). That means that the usual expectations of multiple inheritance and the mro aren't really honored. Any chance of fixing this?

Otherwise, I am loving this package, thanks so much for making it available.

**Comment by aleneum** [comment]
Yeah,

this happens when Machine is not the 'last in line'. I see where Machine calling super could be useful. To estimate the changes required it would be nice to know if you also plan to inherit from `State`, `Transition` or `Event`.

**Comment by aleneum** [comment]
Additionally,

could you provide a minimal example of your inheritance scenario to test against.

**Comment by jonathanunderwood** [comment]
In my work to date, I haven't needed to inherit from State, Transition, or Event - I've only inherited from Machine and HirearchicalStateMachine - I can imagine inheriting from the other extended Machines too.

The issue is actually two things: calling super, and also handling args and keyword args in a way that init functions through the MRO can extract their parameters as needed. 

Here's a simple example for the Machine class. Notice that when creating the D instance, neither A or B's init functions are called:

```python
from transitions import Machine

class A(object):
    def __init__(self, *args, **kwargs):
        print('A init')
        super(A, self).__init__(*args, **kwargs)

class B(object):
    def __init__(self, *args, **kwargs):
        print('B init')
        super(B, self).__init__(*args, **kwargs)

class C(A, B):
    def __init__(self, *args, **kwargs):
        print('C init')
        super(C, self).__init__(*args, **kwargs)

class D(Machine, A, B):
    def __init__(self, *args, **kwargs):
        print('D init')
        super(D, self).__init__(*args, **kwargs)


print('Making a C instance:')
c = C()

print('Making a D instance:')
d = D()
```

**Comment by jonathanunderwood** [comment]
Here's a slightly more complicated example showing how arg and keyword arg handling should work...

```python
from transitions import Machine

class A(object):
    def __init__(self, aarg, *args, **kwargs):
        print('A init, aarg:{0}'.format(aarg))
        super(A, self).__init__(*args, **kwargs)

class B(object):
    def __init__(self, barg, *args, **kwargs):
        print('B init, barg:{0}'.format(barg))
        super(B, self).__init__(*args, **kwargs)

class C(A, B):
    def __init__(self, carg, *args, **kwargs):
        print('C init, carg:{0}'.format(carg))
        super(C, self).__init__(*args, **kwargs)

class D(Machine, A, B):
    def __init__(self, darg, *args, **kwargs):
        print('D init, darg:{0}'.format(darg))
        super(D, self).__init__(*args, **kwargs)


print('Making a C instance:')
c = C(aarg='John', barg='Paul', carg='George')

print('Making a D instance:')
d = D(aarg='John', barg='Paul', carg='George', darg='Ringo',
      states=['a', 'b', 'c'], transitions=[['A', '*', 'a'], ['B', '*', 'b'], ['C', '*', 'c']])

```

**Comment by aleneum** [comment]
Very nice examples 👍 

if I call C(foo="bar") in your first example I will get errors since not all parameters were consumed and end up in `object`:

```bash
Making a C instance:
C init
B init
Traceback (most recent call last):
  File "inh2.py", line 25, in <module>
    c = C(foo="bar")
  File "inh2.py", line 16, in __init__
    super(C, self).__init__(*args, **kwargs)
  File "inh2.py", line 5, in __init__
    super(A, self).__init__(*args, **kwargs)
  File "inh2.py", line 11, in __init__
    super(B, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes no parameters
```

It might be possible to inspect the MRO and only call super if next in line is not `object` but maybe you can think of a better solution.

**Comment by jonathanunderwood** [comment]
Informative Stackoverflow on argument passing in multiple inheritance:

http://stackoverflow.com/questions/34884567/python-multiple-inheritance-passing-arguments-to-constructors-using-super

**Comment by jonathanunderwood** [comment]
Yes - I think that's the right outcome though - none of the init functions were expecting a keyword argument 'foo' so you get an error...

**Comment by jonathanunderwood** [comment]
Here's another variant based on the Stackoverflow article...

```python
from transitions import Machine

class A(object):
    def __init__(self, aarg, **kwargs):
        print('A init, aarg:{0}'.format(aarg))
        super(A, self).__init__(**kwargs)

class B(object):
    def __init__(self, barg, **kwargs):
        print('B init, barg:{0}'.format(barg))
        super(B, self).__init__(**kwargs)

class C(A, B):
    def __init__(self, carg,  **kwargs):
        print('C init, carg:{0}'.format(carg))
        super(C, self).__init__(**kwargs)

class D(Machine, A, B):
    def __init__(self, darg, **kwargs):
        print('D init, darg:{0}'.format(darg))
        super(D, self).__init__(**kwargs)


print('Making a C instance:')
c = C(aarg='John', barg='Paul', carg='George')

print('Making a D instance:')
d = D(aarg='John', barg='Paul', carg='George', darg='Ringo',
      states=['a', 'b', 'c'], transitions=[['A', '*', 'a'], ['B', '*', 'b'], ['C', '*', 'c']])
```

**Comment by aleneum** [comment]
> Informative Stackoverflow on argument passing in multiple inheritance:

I agree that an extra **kwarg field (like pylab does it for instance) is the least invasive way to achieve the desired behaviour. I already tested it and it seems to work fine until `kwargs` contain some parameters when passed to `object`. As you said, that is intended behaviour but I think it would be nice to process this case to prevent weird error messages for library users. I'd rather expect an Error Message like `Machine does not know keyword 'foo'` instead of `object.__init__() takes no parameters`

**Comment by jonathanunderwood** [comment]
> As you said, that is intended behaviour but I think it would be nice to process this case to prevent weird error messages for library users. I'd rather expect an Error Message like Machine does not know keyword 'foo' instead of object.__init__() takes no parameters

Well... if you're playing around with multiple inheritance, you tend to know enough to be able to work out why that error message occurs. I'm not sure the complexity of calculating the next object in the MRO inside each init function is really worth the benefit to the user. But hey, it's your project and code :)

**Comment by aleneum** [comment]
> Well... if you're playing around with multiple inheritance, you tend to know enough to be able to work out why that error message occurs.

agree! However, the error also occurs if you try to create a 'simple' Machine with a wrong argument even if you do mess around with inheritance. Right now `Machine(foo="bar")` would not complain. With a super call it will raise a `TypeError`. 

I also think there is no easy way to work around this. So a try/except block is probably enough.

I integrated your input into pull request #114. Let's see what the others say. Many thanks for your input!

best regards,
Alex

**Comment by jonathanunderwood** [comment]
Great, thanks Alex.

**Comment by jonathanunderwood** [comment]
Do you plan to add the same capability to the extended machines - although I was using Machine for illustration, I actually think it needs adding to the others too for consistency - I was actually using HirearchicalStateMachine in my use case.

**Comment by aleneum** [comment]
`HierarchicalMachine` already works with `*args` and `**kwargs` and just passes arguments to `Machine`. As far as I can tell, solving the issue for Machine should also solve it for all subclasses.

From `nested.py`:

```python
class HierarchicalMachine(Machine):
    def __init__(self, *args, **kwargs):
        self._buffered_transitions = []
        super(HierarchicalMachine, self).__init__(*args, **kwargs)
...
```

Do I miss something?

**Comment by jonathanunderwood** [comment]
Hah, no you didn't miss anything - in fact I now remember that was why I used Machine in the examples! I must be getting tired :)
