### ISSUE TITLE
Semantics of HierarchicalStateMachine

### ISSUE THREAD

**Issue by jonathanunderwood** [tyarkoni/transitions#113]
Using the example given in the README for the heriarchical state machine variant, if one executes

```python
machine.to_caffeinated_dithering()
```
then I think it would make sense for this to return `True`:

```python
machine.is_caffeinated()
```
whereas at present it returns `False` since caffeinated_dithering is a sub-state of caffeinated (of course, `machine.is_caffeinated_dithering()` returns `True`).

I realize this would break backwards compatibility, so perhaps such a change would be activated by supplying a keywrod argument to the __init__ function of HSM.

**Comment by aleneum** [comment]
Hi @jonathanunderwood,

nice idea. What about this: is_state could accept a `strict` keyword which allows substates:

```python
machine.state # caffeinated_dithering
machine.is_caffeinated() # returns True
machine.is_caffeinated(strict=True) # returns False
```

Question is, if strict should be default true or false.

**Comment by jonathanunderwood** [comment]
Yes, that is a nice interface design, I agree. "specific" might be a better keyword than "strict", but that's just bike shedding on my part.

If you don't want to break people's existing code, I think you'd want strict to default to True.

**Comment by jonathanunderwood** [comment]
Wow, that was quick work, many thanks!

**Comment by aleneum** [comment]
see merge
