### ISSUE TITLE
* not working as expected with nesting

### ISSUE THREAD

**Issue by ajax2leet** [tyarkoni/transitions#116]
Consider following example
```python
from transitions.extensions import HierarchicalMachine as Machine
ms = Machine(states=["C","D"],
             transitions={"trigger":"go","source":"*",
                               "dest":"D"},initial="C")

m = Machine(states=["A","B",{"name":"NEST","children":ms}])
m.to_NEST_C() 
m.go() # works

m.to_NEST() 
m.go() # raises MachineError
```
It seems that "*" doesn't refer to states of the parent machine, or is this intended behaviour?

Edit: It appears that "*" can only add transitions for states, that are known, when add_transition is called. But I still think the example given above should work

**Comment by aleneum** [comment]
your guess is right. '*' is resolved into all available states. When embedding a machine into another '*' transitions are not longer known. Thanks for pointing this issue out. I will have a look at it asap.

**Comment by aleneum** [comment]
Just go give you a small update on this:
Unfortunately, it would require quite some rework to treat wildcards in a way that allows them do be identified as wildcards later on. There are some 'quick fixes' I can think of which may work for certain scenarios but not all of them. Some things to consider are:

* adding a transitions: if its a wildcard transition add them to all states
* adding a state: if there is any wildcard transition, find it and add the state to the valid transition sources
* execution hierarchy: if transitions are handled separately (wildcard and specific; this would solve the first two questions) should wildcard transitions *overwrite* other transitions or being handled only if there is no other option? 
* graphs: how to visualize wildcard transitions? Right now `GraphMachine` treats every transition equally. Having two separate sets of transitions makes this more complicated.

Additionally, I can think of situations where the 'isolation' of wildcards to substates may be desired behaviour. `restart` for instance might be used to reset a machine but maybe should not reset the parent machine when embedded. If 'global' transitions are required, they can be added to the parent machine.

That being said, I do not think it is impossible to achieve. I just fear it makes simple use cases more difficult. If you have more thoughts on this let me know.

**Comment by aleneum** [comment]
Due to lack of feedback I will close this for now. Feel free to reopen it if you have some ideas or new insights/feedback.

**Comment by khigia** [comment]
Not directly related but I had a similar issue when I wanted to graph the * transition.
What I did is an abstraction to describe the state machine, and only when want to use it I create an instance of the state machine using transition lib. That way the abstraction can do the graphing, showing * etc and even having more properties for node and edge.
I think it would be too much of design change for this lib though.

**Comment by aleneum** [comment]
That does sound interesting. Do you have a code snippet or link so that I(or @ajax2leet, maybe) can have a look at how you have done it?

**Comment by khigia** [comment]
I can't provide code (sadly it's not not open source). But the idea is quite simple. I created a `AbstractMachine` class, passing the full description at once (I believe it is important to see the transition matrix in one place, not building it iteratively). So it looks like:
```
machine_factory = AbstractMachine([
  S('state1': [
    Tr('event0', 'state2'),
    Tr('event1', 'state3', condition='cond0'),
  ],
  S('state2': [
    Tr('event0', 'state1'),
  ],
])

machine_representation = machine_factory.graph() # create a graph
machine = machine_factory.make(...) # create and return a transition lib Machine type
```
This purposely remove dynamic creation of state, event, transition etc and force user to define the full machine at once (because that is what we use state machine for, for making explicit transition and states).
Hope it help.
