### ISSUE TITLE
Can auto transition support conditional and call back

### ISSUE THREAD

**Issue by afterlastangel** [tyarkoni/transitions#118]
Hello @tyarkoni , I'm very interested in your transitions module, It help me maintain the object state and build the flow control for our object. Currently the conditional for permission check and callbacks for task execution. But I wonder if we might support auto transitions to another state but checking the condition and triggering the callback too? It's very useful to do all the flow with just one call.

**Comment by tyarkoni** [comment]
You can already have default callbacks by passing `before_state_change` and `after_state_change` to the Machine initializer. I agree that it might be desirable to also have a default set of conditionals that get checked on every transition (and I think this has been raised before). That said, I'm not so keen on adding yet another argument to the initializer. As it stands, we already lack a `prepare_state_change` argument in the initializer that would be equivalent to the way before and after are handled. So at minimum we're looking at adding two more arguments to get a more consistent API.

I think my preferred way to handle this would be to introduce a new `TransitionDefaults` object (could be just a dict, or possibly an instance of class `Transition`) that stores the configuration for all parameters that should be applied by default to all new `Transition` instances. That would include the callbacks `before`, `after`, and `prepare`, as well as `conditions`, `unless`, and anything else we want to have a default for. Then the user would only have to pass an optional object to the `transition_defaults` argument in the initializer. Seems much cleaner to me that way. Thoughts, @aleneum, @wtgee?

**Comment by afterlastangel** [comment]
Thanks tyarkoni, 
I found the after_state_change that is not mentioned in the homepage. It's useful for me to set the object model state by the machine state. TransitionDefaults is a good idea but it's not our priority right now. 
Your library is very clean and extensible. I built some helpers to get the possible states and triggers from current state (I got idea from your HSM) for my project. 
I hope to contribute to this project in near future )

**Comment by aleneum** [comment]
I agree with what @tyarkoni said. Subclassing `Transition`, `State` or `Machine` is the way to go here. I always considered `auto_transition` to be some kind of 'developer feature' with a guaranteed transition. Imho, this does not involve preparations and checks. I'd rather have a set of custom methods (e.g. `conditional_to_*`) to distinguish them from auto_transitions. It's basically a two line of code loop over all states which adds a wildcard transitions for every state. But maybe that is just me. 

@afterlastangel: Thank you for pointing out the documentation gap. I added a passage which hopefully will make this feature easier to spot for developers in the future.
