### ISSUE TITLE
Graph Multiple Transitions to Same State

### ISSUE THREAD

**Issue by Cabalist** [tyarkoni/transitions#121]
This might be an issue with my understanding of state machines but I am seeing unexpected results when creating a graph.

I have a machine that when it is "hot" it turns "off".  If it detects "hot" while it is off it stays off.  If it detects "warm" while it is off it stays off.   I expect in the graph generated that it would have two self-referential arrows.   Instead I am seeing just one for the last transition that I defined.

Example code:

```python
class DemoIssue(object):
    states = ["Off",
              "Green Light On"]

    def __init__(self):
        self.machine = Machine(model=self, states=DemoIssue.states, initial='Off', auto_transitions=False)

        self.machine.add_transition(trigger='hot', source="Off", dest="Off")

        self.machine.add_transition(trigger='warm', source="Off", dest="Off")
        self.machine.add_transition(trigger='warm', source="Green Light On", dest="Off")

        self.machine.add_transition(trigger='cold', source="Off", dest="Green Light On")
        self.machine.add_transition(trigger='cold', source="Green Light On", dest="Green Light On")
```

Example Graph:
![my_state_diagram](https://cloud.githubusercontent.com/assets/828557/16902760/2bacaf40-4c1d-11e6-96fb-a96e41a3c794.png)

**Comment by wtgee** [comment]
Hi @Cabalist It looks like you are just running an older version of the code. Here's what I'm getting:

![foo](https://cloud.githubusercontent.com/assets/70736/16903187/7254acfc-4cba-11e6-82a3-1435e196eebe.png)

**Comment by Cabalist** [comment]
Excellent!  I just did a pip install. I'll pull from the repo. Thanks!
