### ISSUE TITLE
add aliases

### ISSUE THREAD

**Issue by julianhille** [tyarkoni/transitions#125]
i would like to see aliases which are just another name for the exact same transition.

**Comment by wtgee** [comment]
Hi @julianhille. That's an interesting idea but not one we've heard that is in high demand. We are trying to keep the library fairly simple and I don't think a lot of people would necessarily have that need, although I can definitely see some uses. Can you provide an example of what you are looking for and how you want to use it.

**Comment by julianhille** [comment]
I've got some fairly complex logic behind some of my transitions. But this specific state has a specific name called "new_data_received" all this logic now is also needed at a another transition which has nothing in common with the old one in case of naming or the cause of the transition only the result/logic is the same.

At first i thought about doing just a copy of that transition and give it another name and call internally another function, but then i would have had to copy also a huge amount of unit tests. These are testing the set up of these transition, so this wasn't an option (don't add tests wasn't one either).

Aliases didn't exist and so i just added a function to my state machine which calls the other transition but that will lead to a "wrong" log entries.

so i thought this would be best implemented as a list of aliases possible to configure at the level of a transition.

**Comment by wtgee** [comment]
My feeling is that it's not something we would want to support in the main code. If you write it up and do a pull-request we could look into it further but doesn't seem like it would be used frequently. @tyarkoni @aleneum ?

**Comment by tyarkoni** [comment]
I don't really like the idea of adding functionality for this specific use case to `core.py`. I think what you want to do can probably be done fairly easily by just copying the old transition to a dummy new one. Something like this should work:

```python
from copy import copy
from transitions import machine

class Model(object): pass

lump = Model()
m = Machine(lump, states=['A', 'B', 'C'], initial='A')
m.add_transition('move', 'A', 'B')
m.add_transition('also_move', 'A', 'C')

# Copy the 
old_transition = m.events['move'].transitions['A']
m.events['also_move'].transitions['A'] = copy(old_transition)

# Should print 'B' rather than 'C'
lump.also_move()
```

I haven't extensively tested the above, but I don't think the replacement should have any side effects.

If the above code works without any problems, we could consider creating a new utils module and adding the above code there as `alias_transition()` or something like that. Given that the aliasing can be done in two lines of code, I'm not sure it's worth it, except perhaps insofar as it alleviates the need to understand the internal Model --> Events --> Transitions structure.

**Comment by aleneum** [comment]
Maybe one could add a method to the model:

```python
class Model(object):
    def add_alias(self, alias, target):
        if not hasattr(self, target):
            raise ValueError('Model does not contain target method %s' % target)
        elif hasattr(self, alias):
            raise ValueError('Model already contains method with name %s' % alias)
        else:
            setattr(self, alias, getattr(self, target))
```

Can be used like this:

```python
model = Model()
states = ['stopped', 'walking']
transitions = [
    ['walk', 'stopped', 'walking'],
    ['stop', 'walking', 'stopped']
]
machine = Machine(model, states=states, transitions=transitions, initial='stopped')
print model.state # >>> stopped
model.walk()
print model.state # >>> walking
model.add_alias('stroll', 'walk')
model.add_alias('pause', 'stop')
model.pause()
print model.state # >>> stopped
model.stroll()
print model.state # >>> walking
# model.add_alias('stop', 'walk') # >>> ... ValueError: Model already contains method with name stop
model.add_alias('patrol', 'stroll')
# model.add_alias('escort', 'travel') # >>> ValueError: Model does not contain target method travel
```

**Comment by tyarkoni** [comment]
That's a better solution. And we could still potentially add a helper method in a utils module, saving users from having to write their own add_alias method. It would be identical to your version but take the model instance as the first argument.

**Comment by wtgee** [comment]
@julianhille Would the above solution work in your case?

**Comment by julianhille** [comment]
That would depend on what is logged if this happens:

    model.pause()
    print model.state # >>> stopped

but that looks fairly simple and usable to me.

**Comment by aleneum** [comment]
Good point,

in this case it gets a bit more messy:
```python
class Model(object):
        ...
        else:
            target_func = getattr(self, target)
            def alias_func(*args, **kwargs):
                logger.info("Calling alias %s for trigger %s" % (alias, target))
                target_func(*args,  **kwargs)
            setattr(self, alias, alias_func)
```
Output would be something like:

```
MacBook-Pro-3:transitions alneuman$ python aliastest.py 
...
walking
INFO:__main__:Calling alias pause for trigger stop
INFO:transitions.core:Initiating transition from state walking to state stopped...
INFO:transitions.core:Exited state walking
INFO:transitions.core:Entered state stopped
stopped
INFO:__main__:Calling alias stroll for trigger walk
INFO:transitions.core:Initiating transition from state stopped to state walking...
INFO:transitions.core:Exited state stopped
INFO:transitions.core:Entered state walking
walking
```

**Comment by aleneum** [comment]
I will close this for now since it seems like a reasonable solution have been found. Feel free to reopen this issue if you have more feedback.
