### ISSUE TITLE
decide "dest" state based on function output

### ISSUE THREAD

**Issue by kampta** [tyarkoni/transitions#129]
Not exactly an issue, but trying to understand if I can implement the following.

In the example below, if number of states are large, and I want to go to the state, based on the output of function `heat_up`, how would I go  about it? (In the hypothetical example, where `heat_up` is returning a floating point)

```
class Matter(object):
    heat = False
    attempts = 0
    def count_attempts(self): self.attempts += 1
    def is_really_hot(self): return self.heat
    def heat_up(self): self.heat = random.random() < 0.25
    def stats(self): print('It took you %i attempts to melt the lump!' %self.attempts)

states=['solid', 'liquid', 'gas', 'plasma']

transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid', 'prepare': ['heat_up', 'count_attempts'], 'conditions': 'is_really_hot', 'after': 'stats'},
]

lump = Matter()
machine = Machine(lump, states, transitions=transitions, initial='solid')
lump.melt()

machine = Machine(Matter(), states, transitions=transitions, auto_transitions=True, initial='solid')
```

**Comment by tyarkoni** [comment]
There's no built-in handling for this sort of thing; you would just write your own conditional that checks lump.heat and moves to different states depending on its value:

```python
lump.heat_up()
if lump.heat < 0.25:
    lump.do_something_A()
else:
    lump.do_something_B()
```

**Comment by kampta** [comment]
Thanks for the quick reply

**Comment by aleneum** [comment]
You could use the chaining nature of transitions to achieve a similar behaviour. Transitions are checked in the same order they were added.

I adapted your example a bit. We have two transitions with the same trigger.  When the first transition is evaluated `heat_up` is called and if the 'is_really_hot' condition returns `False` the transition is executed since the condition is negated by `unless`. If  'is_really_hot' returns `True`, the second transition will be executed. We could check `conditions: 'is_really_hot` again but since this transition is only evaluated if the first one was rejected, the condition is already given implicitly.

```python
from transitions import Machine
import random

class Matter(object):
    heat = False
    attempts = 0
    def count_attempts(self): self.attempts += 1
    def is_really_hot(self): return self.heat
    def heat_up(self): self.heat = random.random() < 0.5

states=['solid', 'liquid', 'gas', 'plasma']

transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid', 'prepare': ['heat_up'], 'unless': 'is_really_hot'},
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'gas'},
]

lump = Matter()
machine = Machine(lump, states, transitions=transitions, initial='solid')
lump.melt()
print lump.state  # multiple runs return different values: gas, liquid, liquid, liquid, gas...
```

**Comment by kampta** [comment]
Thanks @aleneum,  I ended up doing the similar thing.

I think my problem was more in terms of, like we have this `*` wildcard to go from any state to plasma,

```
{ 'trigger': 'ionize', 'source': '*', 'dest': 'plasma' }
```
can we write something like

```
{ 'trigger': 'melt', 'source': 'solid', 'dest': '*',  prepare': ['heat_up']}
```

where `dest` state  depends on the output of `heatup`

```
def heat_up(self):
    if random.random() < 0.5:
        return 'liquid'
    else:
       return 'solid'
```
