### ISSUE TITLE
a generic callback

### ISSUE THREAD

**Issue by xdmiodz** [tyarkoni/transitions#13]
Hi!

Is there a way to specify a generic callback which will be called whenever the machine changes its state?

**Comment by xdmiodz** [comment]
never mind, I can use a decorator instead

**Comment by tyarkoni** [comment]
I like the idea in principle, and would be happy to consider a PR that adds this relatively unobtrusively (I don't have time to work on it myself right now).

**Comment by tyarkoni** [comment]
Closed in #17
