### ISSUE TITLE
Incorrect order of traces in case of entering new state

### ISSUE THREAD

**Issue by ahmedabt** [tyarkoni/transitions#132]
In method
def enter(self, event_data):
        """ Triggered when a state is entered. """
        for oe in self.on_enter:
            event_data.machine._callback(oe, event_data)
        logger.info("%sEntered state %s", event_data.machine.id, self.name)

The trace is printed after calling the callback function, after entering the state, however it should be before like the following 

def enter(self, event_data):
        """ Triggered when a state is entered. """
        logger.info("%sEntered state %s", event_data.machine.id, self.name)
        for oe in self.on_enter:
            event_data.machine._callback(oe, event_data)

**Comment by aleneum** [comment]
Hi @ahmedabt,

thank you for your feedback. I would actually argue for the current order since the callbacks are part of the entering process which ends when all callbacks have been processed. But that is just my opinion and I also see why the other order may be desirable. Let's see what the others say.

**Comment by wtgee** [comment]
Originally I expected it to be the way that @ahmedabt suggests but have adjusted. We could simply add another logging line that makes it clear it is about to do the callbacks and then keep the line that it has actually entered the state.

**Comment by aleneum** [comment]
What about:
```python
logger.info("%sEntering state %s", event_data.machine.id, self.name)
```
Or a bit more detailled:

```python
logger.info("%sEntering state %s. Processing Callbacks.", event_data.machine.id, self.name)
```

**Comment by tyarkoni** [comment]
I can see arguments for either order (and the same thing goes for the behavior of on_exit()), but I think it's probably a bit late in the game to change this unless there's a clear consensus that the change would make sense (and there doesn't seem to be). @ahemdabt, would a log line like @aleneum suggests be helpful? If not, I suggest we close the issue, though we can always revisit it again in future if there are additional votes for flipping the order.
