### ISSUE TITLE
Logger reports everything on >= INFO, no debug-level used

### ISSUE THREAD

**Issue by ankostis** [tyarkoni/transitions#139]
Excellent library, thank you, and the logging statements are crucially placed.

May I suggest that some logging-statements report on a lower level, e.g. those reporting the execution of some callback, and possibly those reporting pass/fail of failed conditions?
(basically, just keep the Enter/Exit log-statements in info level)

Should I provide a PR?

**Comment by ankostis** [comment]
Also a minor typo [at `core.py#L163`](https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L163) instead of "Executing callback..." --> "Executed callback..."

**Comment by aleneum** [comment]
Thank you for the feedback and I see your point. I guess most output would fit into debug as well.
Since this will change the (maybe expected) logging behaviour for many users, I do not wan't to make the change without consent of @wtgee or @tyarkoni.

**Comment by tyarkoni** [comment]
Yeah, I think this makes sense too. It may break expected behavior for some users, but will be easily fixable by changing log-level for those who need it.

**Comment by wtgee** [comment]
:+1:
