### ISSUE TITLE
more diagram modes

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#147]
I want to propose two new modes/functions for the graphing extension:
- `keyword: filter_auto_transitions` -- having auto transitions enabled causes clutter if state machines become more complex. Imho, they do not add information to the graph because it should be quite obvious how every 'to_'-method works. At the moment I disable auto transitions for 'productive' deployment but I would prefer to have a useful graph AND auto transitions.
- `keyword: roi_only/show_roi_only` -- having a 'focused' view of the graph is another feature that may be useful. Since the state machine I am currently working with has about 15 states (and growing) and most of the time only a fraction of these states is relevant. A focused view would include the last state, (the last successful transition,) the current state and all possible transitions from this state.

The keywords could be part of the constructor or passed to the `get_graph` function. Especially `roi_only` might be something you want to use in conjunction with the 'standard' behaviour and therefore in `get_graph`.

What do you think about this? Any suggestions for the naming of these parameters?

**Comment by wtgee** [comment]
:+1: I think it sounds like a good idea and I could see both of them being useful.

Does it make sense to automatically filter the auto transitions and then make the keyword `display_auto_transitions`? It might lead to some confusion if people don't read the docs carefully enough.

(Also, sorry for ignoring this for 17 days...)

**Comment by tyarkoni** [comment]
Sorry, I also missed this. +1 on both ideas as well. And also +1 on @wtgee's suggestion to not display auto_transitions by default, and call the flag `display_auto_transitions` (or maybe `show_auto_transitions`).

**Comment by aleneum** [comment]
* added `show_roi` to `get_graph` function which is attached to the model.
* added `show_auto_transitions` (default False) to `GraphMachine.__init__`

both has been integrated into `dev-0.5`
