### ISSUE TITLE
Bind callback to function reference not function name string

### ISSUE THREAD

**Issue by PaleNeutron** [tyarkoni/transitions#149]
I have asked a question [In transitions,how to define a callback function by function reference not by function name string](http://stackoverflow.com/questions/39991657/in-transitions-how-to-define-a-callback-function-by-function-reference-not-by-fu)

**Comment by tyarkoni** [comment]
Thanks--closing this here in favor of discussion on SO. But the short answer is that this isn't supported and is unlikely to be added. Sorry!

**Comment by tyarkoni** [comment]
Actually, I take that back--my mistake. In theory this *should* already work. So will treat it as a bug.

**Comment by tyarkoni** [comment]
Looks like it works fine; the fix is on SO. Closing issue.

**Comment by tyarkoni** [comment]
Okay, looks like there was a bug in the handling of the `prepare` callback--it wasn't handling callables properly, just strings. Should be fixed as soon as @aleneum or @wtgee merge the PR I just opened. Thanks, @PaleNeutron!
