### ISSUE TITLE
Add possibility to use State object references when calling add_transition

### ISSUE THREAD

**Issue by gangefors** [tyarkoni/transitions#153]
Right now it seems that it's only possible to add transitions by using strings of the state names but not State object references when calling add_transition.

If support was added it would open up for code completion in editors and easily finding misspelled state references since they will be found by static code analysis/pylint.

```
>>> from transitions import State, Machine
solid = State('solid')
liquid = State('liquid')
machine = Machine(states=[solid, liquid], initial=solid)
machine.add_transition('melt', solid, liquid)
machine.melt()

Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/home/stefanga/.virtualenvs/reactor/lib/python3.4/site-packages/transitions/core.py", line 531, in add_transition
    for s in source:
TypeError: 'State' object is not iterable
```

A possible workaround right now is to create "constants" for the state names and use them, but the example above feels much more object oriented and I was suprised that it didn't work.

**Comment by aleneum** [comment]
Hello @gangefors,

thank you for your feedback. `State` objects have a `name` attribute. Your typo argument is valid and can currently be avoided with:

```python
machine.add_transition('melt', solid.name, liquid.name)
```

Let's see what the others think. I am okay with using strings for add_transition but also see the advantage of passing objects (and maybe checking if the states are actually in the machine).

**Comment by tyarkoni** [comment]
This seems reasonable to me, so I opened a PR for it. I do worry that at some point core.py will start to get really cluttered if we keep adding this kind of functionality, but since this patch was pretty trivial, I think it's fine.

I haven't add checking to see if states exist yet, but I agree it would make sense to do that, @aleneum . Let's open a separate issue for that though.

**Comment by gangefors** [comment]
Wow, that was really fast. :+1: 

Thanks a lot for handling this issue so fast. Feels like I made the right decision when I chose transitions for my state machine implementation, both feature-wise and issue response time.
