### ISSUE TITLE
Check existence of States named in add_transitions

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/transitions#155]
Per @aleneum's comment in #153, it would make sense to check that States named in the `source` and `dest` arguments to `add_transition` actually exist. The only potential drawback I can see is it's conceivable someone might want to add transitions involving states that don't exist yet (e.g., perhaps the source `State` is expected to be added dynamically later). If we think the latter is likely to be a real (if rare) use case, I would lean towards not implementing name checking, since I don't think we want to start adding a Machine-level flag for something like this (i.e., an option that overrides the default checking behavior). Otherwise we should probably raise an Exception whenever a non-existent state is invoked.

**Comment by aleneum** [comment]
I also think of transitions' 'lazy evaluation' as a feature. For strings I'd keep that behaviour.
I was just thinking about the following case: If you use `State` objects for adding transitions, you might want to make sure this is the actual state object and not just one that has the same name.

```python
machine.add_state('A')
machine.add_state('B')
state_A = State('A', on_enter='fancy_things')
machine.add_transition('go', state_A, 'B')
machine.go() # no fancy things happening
```

**Comment by tyarkoni** [comment]
Oh, I see. Yeah, that makes sense.
