### ISSUE TITLE
Add Markovian functionality.

### ISSUE THREAD

**Issue by merinom** [tyarkoni/transitions#159]
Do you have in mind to add probabilities between states to get a Markovian Chain?
Greetings

**Comment by tyarkoni** [comment]
I don't think it's on the agenda right now, but in principle, it probably wouldn't be very difficult to add probabilistic transitions via a subclass that only triggers its parents execution methods with some (predefined) probability.

**Comment by merinom** [comment]
Okey!, thank you for responding so quickly, I'll see what I can do.

**Comment by tyarkoni** [comment]
Actually, on second thought, I'm not sure it's worth tinkering with the package code for this. Depending on your use case, you might be able to do what you want just by setting up a transition probability matrix yourself, and firing (still deterministic) triggers based on that. I.e., suppose you have three states in your machine, and you can transition between any two states *i* and *j* with some fixed probability *p_ij*. Then you could have something like:

```python
class TransitionMatrix(object):
    p = np.array(([0.3, 0.1, 0.6], [0.2, 0.5, 0.3], [0.6, 0.4, 0.0]])

    def move(self, machine):
        # figure out the index of the current state
        i = machine.state.get_index()
        # get the target state probabilistically
        target = np.random.choice(np.arange(3), p=self.p[i])
        # move to the target
        state_name = machine.states.keys()[i]
        machine.set_state(state_name)
```

The above definitely won't work (for one thing, there's no `get_index` method), but hopefully it gives the general idea. Feel free to elaborate on your use case if this doesn't quite get at what you intend.

**Comment by renatosamperio** [comment]
This looks useful!

**Comment by merinom** [comment]
I thought about something similar to that, but your solution is clearer. 
Thank you again. I'm sure that this topic will be useful to more people.

**Comment by felicitia** [comment]
just following up on this. Are weights/probabilities of the transitions supported now or we should write our own solution like listed above?

**Comment by aleneum** [comment]
Hello @felicitia,

this is still the preferred way. If you also need to trigger `before/exit/enter/after` callbacks, you could use `Machine.trigger` to dynamically create (auto) transitions:

I adjusted Tal's example accordingly:

```python
from transitions import Machine
import numpy as np


class TransitionMatrix(Machine):
    p = np.array([[0.3, 0.1, 0.6], [0.2, 0.5, 0.3], [0.6, 0.4, 0.0]])

    def move(self):
        keys = list(self.states.keys())
        i = keys.index(self.state)
        target = np.random.choice(np.arange(3), p=self.p[i])
        state_name = keys[target]
        self.trigger(f'to_{state_name}')


m = TransitionMatrix(states=['A', 'B', 'C'], initial='A')
assert m.is_A()
m.move()
print(m.state)
```

**Comment by felicitia** [comment]
got it thanks for the quick reply @aleneum !
