### ISSUE TITLE
Optional debugging feature

### ISSUE THREAD

**Issue by lulingar** [tyarkoni/transitions#16]
This library is very useful, thanks for the great work!

I think that adding an optional logging feature, which would dump to stdout/err all transitions as they get triggered, along with the states which they originate from/go to, would be a big convenience.

**Comment by tyarkoni** [comment]
Great idea! I won't have time to take this on for a couple of weeks, but would be very happy to consider PRs.

**Comment by lulingar** [comment]
I would love to contribute, but in quick reading `core.py` I got a little overwhelmed since the code, despite being well written, is rather long. If you have a suggestion where I could add logging hooks safely, I would give it a shot.

**Comment by tyarkoni** [comment]
Sure--let me get back to you after Friday. :)

**Comment by tyarkoni** [comment]
Sorry @lulingar, just realized I never followed up on this. I just added very basic logging in a17617e4d5480. This could be improved in various ways (e.g., assigning all logged events to named constants, adding messages for other events, allowing writing to file, or adding metadata like timestamp and Machine instance to the logs). All logged events are at INFO level right now, and I haven't changed the default loglevel, so to output the logs to stdout, one just has to import the logger from the module and set its level appropriately before running. I.e.,

```python

import logging
from transitions import logger
logger.setLevel(logging.INFO)
```

Then you should have a record of transitions, state changes, and fired callbacks.

I'm closing this for now, but feel free to re-open if any issues arise.
