### ISSUE TITLE
Remove trigger from Machine

### ISSUE THREAD

**Issue by PaleNeutron** [tyarkoni/transitions#162]
How to remove a trigger from a Machine if I do not whant to re-initialize a new Machine.

**Comment by aleneum** [comment]
Hmm...

good point. I thought `del machine.events[trigger]` would do the trick but it does not. The `Event` object is still bound to (a) model instance(s). It seems like we have to remove the bound method explicitly from the relevant models. I guess this in future releases this could be done by `transitions` (if the others agree). However, for now this might be a quick fix for you:

```python
from transitions import Machine

states = ['A', 'B', 'C']
transitions = [['go', 'A', 'B']]

def remove_trigger(machine, trigger):
    for m in machine.models:
        delattr(m, trigger)
    del machine.events[trigger]

class Model():
    pass

model = Model()
machine = Machine(model, states=states, transitions=transitions, initial='A')
model.go()
print(model.state)
model.to_A()
remove_trigger(machine, 'go')
try:
    model.go()
except AttributeError:
    pass
print(model.state)
```

**Comment by tyarkoni** [comment]
This is an interesting issue, because in principle the user could want to delete either an entire trigger, or just a particular transition, and we currently don't support the ability to do either. Maybe the way to go about this would be a more general `remove_transition` method to parallel `add_method`, where you can specify any combination of `trigger`, `source`, and `dest`, and the most inclusive set is removed (i.e., if you only specify `trigger`, the trigger is deleted along with all corresponding `Transition`s; if you specify a `trigger` and `dest`, all matching `Transition`s are removed, but the trigger is retained as long as there's at least one `Transition` with the same trigger but a different `dest`, and so on.

**Comment by aleneum** [comment]
Sounds like a plan! I wonder if we might should use wildcards '*' as default values for `source` and `dest`. Otherwise the parameters change their meaning depending on the other value:

* if source is X (and dest is None): remove only t where t.source is X (and ignore dest)
* if dest is X (and source is None): remove only t where t.dest is Y (and ignore source)
* if source is X and  dest is Y: remove only t where t.source is X and t.dest is Y
* if source AND dest are None: remove ALL

Or as a sentence: None for one parameter means 'ignore this unless the other parameter is None as well'. This might lead to some confusion. What do you think?

def remove_transition(trigger, source="*", dest="*") may solve this.

**Comment by aleneum** [comment]
My first attempt. It also allows passing lists of sources and destinations. About the attempt: Even though list comprehension is not the most... comprehensible... solution it saves some assignments during the filtering process. I haven't found a neat way without many assignments AND just one dictionary iteration. If you see room for improvement, give me a shout.

```python
from transitions import Machine
from transitions.core import listify

states = ['A', 'B', 'C']
transitions = [['go', 'A', 'B'],
               ['go', 'B', 'C']]

def remove_transition(machine, trigger, source="*", dest="*"):
    source = listify(source) if source != "*" else source
    dest = listify(dest) if dest != "*" else dest
    # outer comprehension, keeps events if inner comprehension returns lists with length > 0
    machine.events[trigger].transitions = {key: value for key, value in
                                           {k: [t for t in v
                                                # keep entries if source should not be filtered
                                                if (source is not "*" and t.source not in source)
                                                # same for dest. One condition has to be true for the entry to be kept
                                                or (dest is not "*" and t.dest not in dest)]
                                                # }.items() takes the result of the inner comprehension and uses it
                                                # for the outer comprehension (see first line of comment)
                                                for k, v in machine.events[trigger].transitions.items()}.items()
                                                if len(value) > 0}
    # if no transition is left remove the trigger from the machine and all models
    if len(machine.events[trigger].transitions) == 0:
        for m in machine.models:
            delattr(m, trigger)
        del machine.events[trigger]

class Model():
    pass

model = Model()
machine = Machine(model, states=states, transitions=transitions, initial='A')
model.go()
model.to_A()
remove_transition(machine, 'go', ['A'])
print(machine.events['go'].transitions)
```

**Comment by aleneum** [comment]
We might also want to support remove_transition(transition) for cases in which source and dest are equal but 'before', 'after' etc. are different.

**Comment by aleneum** [comment]
implemented `remove_transition` as described here in `dev-0.5`

**Comment by hookokoko** [comment]
> My first attempt. It also allows passing lists of sources and destinations. About the attempt: Even though list comprehension is not the most... comprehensible... solution it saves some assignments during the filtering process. I haven't found a neat way without many assignments AND just one dictionary iteration. If you see room for improvement, give me a shout.
> 
> ```python
> from transitions import Machine
> from transitions.core import listify
> 
> states = ['A', 'B', 'C']
> transitions = [['go', 'A', 'B'],
>                ['go', 'B', 'C']]
> 
> def remove_transition(machine, trigger, source="*", dest="*"):
>     source = listify(source) if source != "*" else source
>     dest = listify(dest) if dest != "*" else dest
>     # outer comprehension, keeps events if inner comprehension returns lists with length > 0
>     machine.events[trigger].transitions = {key: value for key, value in
>                                            {k: [t for t in v
>                                                 # keep entries if source should not be filtered
>                                                 if (source is not "*" and t.source not in source)
>                                                 # same for dest. One condition has to be true for the entry to be kept
>                                                 or (dest is not "*" and t.dest not in dest)]
>                                                 # }.items() takes the result of the inner comprehension and uses it
>                                                 # for the outer comprehension (see first line of comment)
>                                                 for k, v in machine.events[trigger].transitions.items()}.items()
>                                                 if len(value) > 0}
>     # if no transition is left remove the trigger from the machine and all models
>     if len(machine.events[trigger].transitions) == 0:
>         for m in machine.models:
>             delattr(m, trigger)
>         del machine.events[trigger]
> 
> class Model():
>     pass
> 
> model = Model()
> machine = Machine(model, states=states, transitions=transitions, initial='A')
> model.go()
> model.to_A()
> remove_transition(machine, 'go', ['A'])
> print(machine.events['go'].transitions)
> ```

I think this situation also needs to be considered. It will remove trasition fail when the source/target is of Enum type, because Enum('source') is not equal to 'source'. This could be confusing otherwise.

```
target_source = source.name if hasattr(source, 'name') else source if source != "*" else ""
target_dest = dest.name if hasattr(dest, 'name') else dest if dest != "*" else ""
```
