### ISSUE TITLE
Passing data to multiple callbacks bound to a transition trigger fails

### ISSUE THREAD

**Issue by valste** [tyarkoni/transitions#163]
Hi thx for a nice tool!

Consider the following transition: 
{'trigger': 'connected', 'source': 'EstablishingWsConnection', 'dest': RequestingBN_WaitingForResponse', 'after':['sendBN','updateNrOfAttempts']},
Callbacks: sendBN(self) and updateNrOfAttempts(self, operation). On model.connected(operation='init') : TypeError: sendBN() got an unexpected keyword argument 'operation'. The same error for the flipped version: ['updateNrOfAttempts','sendBN']. 
1) How can I do what I want?
2) Is there any possibilility to pass e.g. three parameters for three callbacks on firing the trigger?

Thanks!

**Comment by aleneum** [comment]
Hello @valste,

`transitions` passes all given parameters to all functions in prepare, check, before and after.
This means your callback methods have to be able to deal with an arbitrary amount of parameters.
Good news: It's pretty easy to do this in python:

```python
from transitions import Machine

states = ['A', 'B']
transitions = [{'trigger': 'connected', 'source': 'A', 'dest': 'B', 'after':['foo','bar','baz']}]

class Model():

    def foo(self, foo, **kwargs):
        print('foo: ' + foo)

    def bar(self, bar, **kwargs):
        print('bar: ' + bar)

    def baz(self, baz, **kwargs):
        print('baz: ' + baz)

model = Model()
machine = Machine(model, states=states, transitions=transitions, initial='A')
model.connected(foo='1', bar='2', baz='3')
```

Best regards,
Alex

**Comment by tyarkoni** [comment]
Alternatively (and more or less equivalently), you can set `send_event` to `True` in the `Machine` initializer, in which case your callback functions should expect to receive an instance of class `EventData` as their first argument, which is basically just a container for keywords. Search for "send_event" in the docs for an example.

**Comment by valste** [comment]
Many thanks!

val
