### ISSUE TITLE
Single state machine, multiple models

### ISSUE THREAD

**Issue by paulbovbel** [tyarkoni/transitions#165]
I may be missing something, but it's definitely possible to:
- create a state machine with an internal model
- create a state machine that managers one or more external models?

Is there any way to define a state machine once, and register model(s) to it after the fact?

Any guidance on the feasibility of implementing something like that?

**Comment by tyarkoni** [comment]
This can't be done right now (well, you *could* just_ append to `machine.models`, and that will give you everything except the ability to register triggers properly), but it makes sense to move the model creation code into an encapsulated `Machine.add_model()` method, and it would be very straightforward.

**Comment by tyarkoni** [comment]
Closed in #166.
