### ISSUE TITLE
Extend lock injection to support simple locks

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#167]
Currently, only reentrant locks are supported by design. A solution would be to check if a lock has been already acquired by the current thread and skip the `LockedMethod/Event` wrapping in this case. Even though `checking` is probably what a RLock is doing anyway this might improve the performance due to the nested nature of method calls. Additionally `transitions` becomes for versatile concerning its interaction with other multithreaded components.

**Comment by paulbovbel** [comment]
In my use case, I'm using re-entrant context managers (an instrumented RLock and django.transaction.atomic), but because of the event frequencies involved, the overhead of triggering the re-entrant behaviour (django generating a save point) ~10+ times for a single trigger is unpleasant.

**Comment by aleneum** [comment]
In `dev-0.5`, we have introduced a custom context manager which will keep track of the thread that currently entered a `with` block. Entering a second time will be omitted. The default locking mechanism still is a `threading.RLock` since `threading.Lock` seems to have issues with pickling.
Additionally, `LockedMethod` wrapping has been reduced to 'public' methods (every method not starting with an underscore) to further reduce the locking overhead.
Considering this simple example

```python
m = M(states=['A', 'B', 'C', 'D'], transitions=[['reset', '*', 'A']], initial='A')
m.get_triggers('A')
```

the following has been achieved:

* reduced execution time from ~600% to ~400% (in contrast to `transitions.Machine`)
* reduced maximum stack size of `with` blocks from 3 to 1
* reduced entering `with` blocks  attempts from 72 (!) to 4

**Comment by paulbovbel** [comment]
Thanks! Looking forward to 0.5
