### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by paulbovbel** [tyarkoni/transitions#168]
Could you please cut a release including:

https://github.com/tyarkoni/transitions/pull/158
https://github.com/tyarkoni/transitions/pull/166

Thanks

**Comment by tyarkoni** [comment]
Good idea, thanks for the reminder. @aleneum, let me know if you want to pull the trigger on PR #151 in the next few days; if so, I'll include it in the 0.4.3 release. Otherwise I'll bump now and we can  add that next time.

**Comment by aleneum** [comment]
Go ahead. A release is a good idea.  #151 takes some more work and I wont be able to tackle this soon. Let's save it for 0.4.4 or later.
