### ISSUE TITLE
after_state_change functionality

### ISSUE THREAD

**Issue by peendebak** [tyarkoni/transitions#170]
Is there a method to change the `after_state_change` callback after the `Machine` object has been created? And is it possible to have multiple callbacks for `after_state_change`. For example:
```
m = Machine(model=some_model, states=[...])
m.add_callback('after_state_change', callback1)
m.add_callback('after_state_change', callback2)
```

**Comment by aleneum** [comment]
Hello @peendebak,

`after_state_change` can handle lists like this:

```python
machine = Machine(..., after_state_change=['callback1', 'callback2'])
```

Additionally, this list can be adapted during runtime as machine property:

```python
machine.after_state_change = 'callback3'
```

However, this will not have any effect on already created transitions and this is probably what you need right?

**Comment by peendebak** [comment]
@aleneum Thanks for the reply. Your example already helps, but I want the callback to apply to already existing states.

After creating a machine with a state and transitions I want to automatically create a GUI that shows the current state and has options to change the state. If the machine changes state through some other way. I want this to be reflected in the GUI. E.g. after changing the state I want to call `gui.update`. 
I create the gui after creating the machine, so the gui can use `machine.states` to build the interface.

**Comment by aleneum** [comment]
Okay,

to achieve this we could convert `Machine.after/before_state_change` into a property

```python
# Machine
@property
def before_state_change(self):
    return self._before_state_change

# this should make sure that _before_state_change is always a list
@before_state_change.setter
def before_state_change(self, value):
  self._before_state_change = listify(value)
```

skip the concatenation during `add_transition` and iterate over two lists (`Transition.before` and `Machine.before_state_change`) with `itertools.chain`

```python
# Transition.execute
from itertools import chain  
for func in chain(self.before, machine.before_state_change):
    ...
```

Let's see what others think of this or if there might be other solutions.

**Comment by aleneum** [comment]
It took a while but since 6e9334f the following should work:

```python
from transitions import Machine


class Model:

    def bark(self):
        print("bark")

    def chirp(self):
        print("chirp")

model = Model()
m = Machine(model=model, states=['A', 'B'], initial='A', before_state_change='bark')

model.to_B()  # >>> bark
m.before_state_change = 'chirp'
model.to_A()  # >>> chirp
```
