### ISSUE TITLE
Reference to 'dest' state on condition callback

### ISSUE THREAD

**Issue by phpepe** [tyarkoni/transitions#173]
Is it possible to get a reference to the destination state on a transition condition callback ?
My implementation has a generic condition code based on : current state, dest state and input data.
I can read input data from kwargs, current_state from EventData, but couldn't find a way to access the dest state (or the current transition object that is being tested)
Thanks in advance for any help

**Comment by phpepe** [comment]
Ok I will answer myself, I just found a reference on the EventData object, so can be done in this way:
```
    def condition(self, event, **kwargs):
        print 'event', event.transition.dest
```

**Comment by wtgee** [comment]
@phpepe I'm closing the issue. Feel free to re-open if you didn't get the answer you need. Thanks!
