### ISSUE TITLE
Why `machine.before` callback happens after `transition.before`?

### ISSUE THREAD

**Issue by ankostis** [tyarkoni/transitions#175]
I think that the order of `machine.before/after` callbacks is a bit asymmetrical.
Currently isolating the order concerning `before/after` events , it looks like that (assuming #174 is correct):

- `transition.before`
- `MACHINE.before`
- `state.exit`
- `STATE CHANGE`
- `state.enter`
- `transition.after`
- `MACHINE.after`

Wouldn't it make sense to "surround" the above block in the machine's default CBs, like that?

- `MACHINE.before`
  - `transition.before`
  - `state.exit`
  - `<STATE CHANGE>`
  - `state.enter`
  - `transition.after`
- `MACHINE.after`

## Rational
I came to question the current ordering because I want to implement a 2-phase commit logic, for all transitions.
So I need to do the 1st phase in `MACHINE.before`, and only finalize it in `MACHINE.after`, if everything was successful.
But any transition-specific login in its `before` cannot access the 1st-phase results (e.g.. a temporary folder, or a branch in some git repo).
And `state.exit` is not specific to the transition (although I can workaround that by checking the destination state from the event-data).

**Comment by aleneum** [comment]
I assume this is just an effect of how it is implemented right now. Imho, it does make sense to call `Machine.before` before `transition.before`. If others agree we can alter the order in no time.

**Comment by wtgee** [comment]
I do think it makes sense to wrap the calls. However I think that might open up the question of what kind of callbacks people will want to write in `MACHINE.before`/`after` such that the question then becomes where do you run the `transitions.prepare`/`conditions`/`unless`. 

Placing the `transition` callbacks inside the `MACHINE`callbacks makes me think that maybe we want the entire `transition` logic called. I'm thinking mostly of something like a custom logger or something else at the `MACHINE` level that would want to help `prepare` a transition or otherwise know about its failure.

**Comment by ankostis** [comment]
(I didn't want to open this can of worms my self... :-)

...but since it's open, I can make a couple more observations:

- Having separate `prepare` methods on each *transition* does not make much sense:
  Why would you "prepare" for a transition that might halt immediately after, in the coming condition?
  A "global" one should suffice.
- I would then couple this new global  `prepare` with a global `finalize` at the end, 
  but only if there is not already some MACHINE at the very end (see case B, below).
- Regarding what you discuss @wtgee , I can see at least 3 possibilities:

Case A: this is my original proposal, where a global `before/after` intermixes with `transition methods:

- `MACHINE.prepare`
  - `transition.condition`
  - `transition.unless`
  - `MACHINE.before`
    - `transition.before`
    - `state.exit`
    - `<STATE CHANGE>`
    - `state.enter`
    - `transition.after`
  - `MACHINE.after`

Case B: *global* `before/after` surrounded by transition methods:
In that case (A) I would prefer to look at them as *global `exit/enter`* methods (not `before/after`):
Notice that there is a need for a global `finalize` method:

- `MACHINE.prepare`
  - `transition.condition`
  - `transition.unless`
  - `transition.before`
  - `MACHINE.exit`
    - `state.exit`
    - `<STATE CHANGE>`
    - `state.enter`
  - `MACHINE.enter`
  - `transition.after`
- `MACHINE.finalize`

Case C: combination of A & B:

- `MACHINE.prepare`
  - `transition.condition`
  - `transition.unless`
  - `MACHINE.before`
    - `transition.before`
    - `MACHINE.exit`
      - `state.exit`
      - `<STATE CHANGE>`
      - `state.enter`
    - `MACHINE.enter`
    - `transition.after`
  - `MACHINE.after`

In order not to proliferate the alternatives, and you have to have a case-study model to judge them (e.g. 2-phase commit processors).
For instance,   the `prepare` is way too early to be used for as the 1st phase because no IDs have been generated yet, and generally, data become available after the conditions.  
So it is the `before/after` and `exit/enter` methods that have to curry the burden of that task.

A final comment is that the code of the project is so well written that it might be possible to support all of the above, and even more (e.g. customizable ordering) without the sources becoming convoluted.

**Comment by aleneum** [comment]
First, thanks for your thoughts. Streamlining this process sounds like a good plan.

> Having separate `prepare` methods on each transition does not make much sense

`prepare` is actually considered to prepare the condition check. There are cases where configurations and checks have to be done before the actual condition check can happen (see #40). Preparing the state change should be done in `before`.

> A "global" one should suffice.

There are cases in which specific preparation does make sense. If you want to construct certain temporal data structures which are later on used by the condition checks, they probably are very specific for the case in question. For instance, if a transition depends on the state of some sensors it would be quite an overkill to always prepare all the sensor data.

> I would prefer to look at them as global exit/enter

Could you elaborate on cases where this could be useful? Right now, `State.add_callback` could be used to trigger certain (global) functions when a state is entered or exited. Are there cases you can think of where this is not enough and execution order (M.before, t.before, M.enter, t.enter, ...) is crucial?  

This being said, at the moment I feel option A with `Machine.prepare` --> `transition.prepare` is sufficient.

**Comment by aleneum** [comment]
> it might be possible to support all of the above 

I agree, if `Machine.enter/exit` are useful additions, option C with proper default values can be configured in a flexible way to resemble the other two options as well. The 'code overhead' should be quite small.

**Comment by ankostis** [comment]
Today I had a nasty bug because there is no global "prepare":  I use the same prepare function on each transition, and most of the cases were running, except for those when the side-effect of the 1st call of prepare fiddled with subesquent calls.  And since the ordering of testing transitions is not deterministic, I was bitten badly.

The bottom line: this excellent lib needs global prepare/finalize - those on transitions are no substitute.

**Comment by ankostis** [comment]
@aleneum thank you for pointing me #40.
From this fruitful discussion I have the following observations to make:

### Firing patter for a new `MACHINE.prepare` callback
I think that the following [question of yours](tyarkoni/transitions/issues/40#issuecomment-177457050) has been neglected:

>  think this 'prepare condition' thing is quite complex. I can think of at least two different scenarios:
> - prepare -> check -> tearDown -> prepare -> check -> tearDown
> - prepare -> check -> check -> tearDown

I vote the 2nd pattern for all cases A, B, C above, for a newly added `MACHINE.prepare`; it should fire only once; it is the per-transition declared `prepare` callbacks that would fire every tried transition.

### Mental rule for introducing new callbacks
Another insight from #40 is that if we are to satisfy all requirements, the callbacks must proliferate.
So I'm proposing as a mental rule to "ban" splitting callbacks between machine & transition/state, unless they have a different firing patter (as is the case for the `MACHINE.prepare` in my paragraph above).

Another way of saying this is that *if a "global" callback can be worked-around by adding the same function to all transitions/states, then this global callback is not needed.*
Note that `MACHINE.before/after` fall in this category, and they have to be removed, if we were to strictly apply this rule.

### Invoking callback with `try...finally`
Finally, I get the feeling that another major functionality, that regards the proposed "shutdown/cleanup" callbacks:  the capability to invoke callbacks even if exceptions have been raised earlier.
What are you thought about that?

### Release plan
I believe that the last 2 points belong to `0.5.0` release, or even better, to `1.0.0`.
Till then, an intermediate `0.4.4` release may add `MACHINE.prepare` and reorder the `MACHINE.before`.

**Comment by aleneum** [comment]
Hi @ankostis,

I need some more input to wrap my head around your bug.

What caused the side effects?
Right now `Machine.before/after` and `Transition.before/after` are just concatenated. If we assume the same pattern for `prepare` the following two cases are more or less identical:

```python
class Model()
    def do_prepare(self, event):
        pass

states = ['A', 'B']
m = Model()

transitionsA = [{'trigger': 'do', 'source': 'A', 'dest': 'B'}]
machineA = Machine(m, states=states, transitions=transitionsA, prepare='do_prepare')

transitionsB = [{'trigger': 'do', 'source': 'A', 'dest': 'B', 'prepare': 'do_prepare'}]
machineB = Machine(m, states=states, transitions=transitionsB)
```

If a chain of possible transitions is checked this would result in
`Machine.prepare -> TransitionA.prepare -> TransitionA.check --(fails)--> Machine.prepare -> TransitionB.prepare -> TransitionB.check ...` and so on.

This is probably not what you have in mind. I assume you require something like this:
`Machine.prepare -> TransitionA.prepare -> TransitionA.check --(fails)--> TransitionB.prepare -> TransitionB.check ...` where Machine.prepare is only called **once** for each trigger, right?

**Comment by ankostis** [comment]
> ...TransitionB.check ... where Machine.prepare is only called once for each trigger, right?

Yes, that's right.
Otherwise, you have to be very careful not to introduce side-effects in machine.prepare among its multiple calls.  

So the `machine.prepare` must not assume the same concatenate pattern.

**Comment by aleneum** [comment]
Okay, about the naming: `Transition.before` relates to `Machine.before_state_change` and `Transition.after` relates to `Machine.after_state_change`. I propose `Machine.prepare_conditions_check` to keep the more descriptive nature of `Machine` attributes.
What do you (@all) think?

**Comment by aleneum** [comment]
Oookay, this might take a bit longer since model convenience functions such as 'before_stateA', 'after_stateA'  and 'prepare_stateA' seem to collide with the solution discussed in #170 when model and machine are the same object.

**Comment by ankostis** [comment]
For the naming I would go for `prepare_all_transitions` - not all transitions have conditions.

**Comment by ankostis** [comment]
What about `finalize_after_all_transitions`?
That may contain an `error` kwarg holding any catched exceptions?

**Comment by aleneum** [comment]
#175 resolved this
