### ISSUE TITLE
Main scheduler

### ISSUE THREAD

**Issue by porceberkeley** [tyarkoni/transitions#18]
Thanks for the nice design and implementation. 

I have a question for the "main" loop. ( I do not know if the "conditional transition" is the answer to my question or not. So please advise )
Let's use your NarcolepticSuperhero example walk-through. You used Python interactive prompt. That's the main loop. It sits there and waits for an event to occur (such as .wake_up()). When that event occurs, the main loop notifies the state machine of that event (batman.wake_up()). That notification makes the state machine transitions to the next state, AND THEN it comes back to the main loop (Python interactive  prompt), and waits again for the next event to occur.

I am seeking a way to implement the Main loop functionality which is not Python interactive prompt. The same functionality is needed: Wait for an event, pass to the state machine so that it can transition to a next state, and completing before_transition(), on_exit(), on_enter(), after_transition(), and THEN  comes back to a main loop.

In the source of "transitions", I found no while loop. 

If this questions does not sound making sense, probably I have mistaken the design of your implementation. 

Thanks,
pb.

**Comment by tyarkoni** [comment]
Not sure I follow... I think the current code does what you describe. If you initialize a state machine and hold on to it in the scope of your executing code, you should be able to call it as needed, and it will block execution until the state machine finishes doing whatever it needs to. If you want to have a *non*-blocking state machine that listens for events on a separate thread, you could do that via message passing or some other concurrency pattern with a bit of work. But you'd need to implement that yourself, as there's no concurrency support at the moment (and none is planned).

**Comment by tyarkoni** [comment]
Closing this, but re-open if you have a follow-up.

**Comment by porceberkeley** [comment]
Thanks again. I think it will be a very useful example if someone comes up with a simple FSM, such as a vending machine, as a self-contained python script, which never exits. (That will also address my original question.)

**Comment by tyarkoni** [comment]
```python
v = VendingMachine()
fsm = Machine(v, states=['rest', 'dispense', 'give_change'])
while True:
    if check_money_in_slot():
        to_dispense()
        to_give_change()
        ...
```

...but note that in practice, you'll probably need to replace the work done here by the check_money_in_slot call with some kind of message passing scheme (e.g., have a look at the [Queue module](https://docs.python.org/2/library/queue.html) in the standard library), or by polling a socket. So I think your question isn't really about FSMs per se, but more generally about how to implement a server in Python. There are plenty of tutorials for that; once you have that down, embedding the FSM logic should be straightforward.
