### ISSUE TITLE
collector.count()  fails in HSM example

### ISSUE THREAD

**Issue by blmd-niz** [tyarkoni/transitions#187]
>   File "testmodel.py", line 38, in <module>
>     collector.count()  # let's see what we got
>   File "/usr/local/lib/python2.7/site-packages/transitions/core.py", line 251, in trigger
>     return self.machine._process(f)
>   File "/usr/local/lib/python2.7/site-packages/transitions/core.py", line 638, in _process
>     return trigger()
>   File "/usr/local/lib/python2.7/site-packages/transitions/extensions/nesting.py", line 136, in _trigger
>     raise MachineError(msg)
> transitions.core.MachineError: "Can't trigger event count from state collecting!"

This would be caused by transitions definition below:
> ['count', 'wait', 'counting_1']

Changing 'wait' to '*' for example will fix issue.

**Comment by aleneum** [comment]
Hi @blmd-niz,

> ['count', 'wait', 'counting_1']

yeah, that is just wrong since there is no state `wait`. This should be `collecting` I guess.
Thank you for pointing that out!
