### ISSUE TITLE
How to get all available transitions for given state?

### ISSUE THREAD

**Issue by pfertyk** [tyarkoni/transitions#189]
I am using the following piece of code:
```
from transitions import Machine
import random

class MyMachine:
    states = ['in_danger', 'victorious', 'defeated', 'escaped']

    def __init__(self):
        self.machine = Machine(
            model=self, states=MyMachine.states, initial='in_danger'
        )
        self.machine.add_transition('run', 'in_danger', 'escaped')
        self.machine.add_transition(
            'fight', 'in_danger', 'victorious', conditions=['made_it']
        )
        self.machine.add_transition('fight', 'in_danger', 'defeated')
        self.machine.add_transition('back', '*', 'in_danger')

    def made_it(self):
        return random.random() < 0.25

mm = MyMachine()
```

I'd like to have a list of available actions (triggers?) for each state (or just the state the machine is currently in). For given example it would look like this:
```
in_danger: run, fight
victorious: back
defeated: back
escaped: back
```
I know I can initialize the state machine with the list of states and transitions, so if I do it that way I will already have available transitions for all states. But is there a way to access this information from the machine itself?

**Comment by aleneum** [comment]
From the README.md:

> If you need to know which transitions are valid from a certain state, you can use get_triggers:
>      m.get_triggers('solid')
>      >>> ['melt', 'sublimate']

is that what you are looking for?

**Comment by pfertyk** [comment]
```
+>>> mm = MyMachine()
+>>> mm.machine.get_triggers('victorious')
['to_victorious', 'to_in_danger', 'to_defeated', 'back', 'to_escaped']
```

Is there a way to leave just the method names? In this case, to skip everything that starts with 'to_' and leave just ['back']? I know I can filter the list manually, but what if I create a trigger that actually starts with 'to_'?

**Comment by aleneum** [comment]
> Automatic transitions for all states
> 
> In addition to any transitions added explicitly, a to_«state»() method is created automatically
> whenever a state is added to a Machine instance. 
> ...
> If you desire, you can disable this behavior by setting auto_transitions=False in the Machine initializer.

**Comment by pfertyk** [comment]
That is exactly what I was looking for ;) Thanks for a quick response and forgive me for not reading the README file closely enough.

The issue can be closed.

**Comment by aleneum** [comment]
no problem. all the best for your project!
