### ISSUE TITLE
Why is Machine invoking super()?

### ISSUE THREAD

**Issue by ankostis** [tyarkoni/transitions#190]
I can see that [`Machine.__init__()` always invokes `super()`](/tyarkoni/transitions/blob/master/transitions/core.py#L363-L366).
In my case, where I have multiple inheritance for `Machine, the above code breaks because the base-classes does not know the machine's kwds. 

Of course I can workaround it, by inheriting that a base-class just to add a dummy `**kwds` in its constructor signature. But still i cannot understand why the machine is invoking super's constructor even if it does not have any base class?

I tried to [search in the issues](https://github.com/tyarkoni/transitions/issues?q=is%3Aissue%20super%20machine) if there is a specific reason for this code, and I'm not sure if that was an explicit decision; So was that one?

**Comment by aleneum** [comment]
I just had a quick look at the blame view of `core` and this is related to #112. It's a feature, not a bug :).
