### ISSUE TITLE
Finish 0.5.0 Release

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#191]
This includes at least:

* update changelog and contributions
* update ReadMe to reflect all the changes that have been done
* tag version

**Comment by aleneum** [comment]
If you feel like something should be added, removed, reviewed or reworded, leave a comment.
In case there are no further remarks, I will tag `0.4.4` next week.

**Comment by ankostis** [comment]
Maybe it should be `0.5.0` because of non-backward compatible changes, such as (at least for what I'm involved) #180, no?

**Comment by aleneum** [comment]
good point.

maybe we should postpone the changes related to `model` and `add_self` to 0.6 then and integrate the dev-0.5 features right away.

**Comment by ankostis** [comment]
From a user perspective, probably it's better to have a single non-compatible bump, with all changes included, instead 2 conjecutive ones (`0.5.x` & `0.6.x`), no?

**Comment by aleneum** [comment]
In #172 we discussed how this change should happen.
A 'soft' transition would be preferable which means that user code does not break instantly and users have at least one version to adapt.
Those changes are mostly related to some corner cases where you want to mix models and machine instances or initialise empty machines. If you follow the `PendingDeprecationWarning` the code won't break (because of the change) when updating from 0.5.0 to 0.6.0.
Actually, *under the hood* these changes have been made already. Most users should not even see the warnings.
0.5.0 for now sounds reasonable.

**Comment by aleneum** [comment]
If there is nothing more to add, I'd suggest to tag 0.5.0 next week.

**Comment by aleneum** [comment]
tagged version 0.5.0
