### ISSUE TITLE
Keywords for ordered_transitions

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#192]
Hi @aforren1,

in aforren1/transitions@cc27263992ead58ce334e5c953a2908320ea39ce you introduced callback keywords for ordered transitions which has been an occasionally requested feature.
Do you consider a pull request?

Best regards,
Alex

**Comment by aforren1** [comment]
Sure! I messed up the merge and fixed a few things, so now it's 7ab6ee5eef7377a12d03aa3518abe81a2240da37 for reference (and PR is #193).

**Comment by aleneum** [comment]
much appreciated! 

thank you!
