### ISSUE TITLE
Question about correct approach for using the state machine in a concurrent way

### ISSUE THREAD

**Issue by luminize** [tyarkoni/transitions#206]
In my situation I'm sometimes waiting in a specific state on a change of an input. And other times I don't have to wait and can continue to go thru states. For example I sometimes need to wait for a CANopen message, or a change of a physical (input)pin 

I could follow a [switch case like approach](http://code.activestate.com/recipes/410692/), where I periodically check the current state, check for a change of input and depending on the result call a transition to go to the next state.

Or should I do this by means of passing a method to the on_enter_<state> callback where in that method I check for the change of input (while loop until input has the correct value) and call the next transition. This seems more natural because I would like to execute some code only in that specific state. But I wouldn't want to block my program.

What would be the best way, or are other solutions to this?

**Comment by aleneum** [comment]
Hi @luminize,

this sounds like a question suitable for Stackoverflow. Posting questions there has the advantage that the community of transitions users (including us) might assist and not just the developers.

Personally, I tackle this issue with an event based approach. Event handling is done by the model and can be either happening by reading from a queue (suited for reading from serial devices) or asynchronously.

```python
from transitions import Machine
from collections import deque
from threading import Thread
from time import sleep

ERROR = -1
READY = 0
BUSY = 1

line = deque()

# simulating a remote device which sends status updates every second
def writer_mock():
    line.append(BUSY)
    sleep(1)
    line.append(BUSY)
    sleep(1)
    line.append(READY)

# read data from line/buffer and trigger events if required
def reader_mock():
    global line, m
    while True:
        # if new messages are available in the buffer, trigger a transition attempt
        if len(line) != 0:
            m.input_received(state=line.popleft())
            if m.state == 'process':
                return
        sleep(0.1)

# condition to check wether a transition should happen
def is_ready(state):
    print("Current state: " + str(state))
    return state == READY


states = ['init', 'waiting', 'process']
transitions = [
        ['initialized', 'init', 'waiting'],
        {'trigger': 'input_received', 'conditions': is_ready, 'source': 'waiting', 'dest': 'process'}
    ]

m = Machine(states=states, transitions=transitions, initial='init')
# if setting up your model requires some preparation, 'after' would be a good 
# spot to open channels/sockets/streams for reading.
# This prevents events appearing before the model is set up
m.initialized()
writer = Thread(target=writer_mock)
writer.start()
# the reader could also run in a thread. But this way it blocks and keeps the program from
# exiting too early
reader_mock()
```

I would recommend to process events synchronously to keep the complexity lower. However, if your event processing cannot be streamlined you can use 'LockedMachine' from the extension module which will lock event processing.

**Comment by luminize** [comment]
@aleneum thanks, I need to look at the extensions 'LockedMachine' and I saw 'Hierarchical State Machine' too. I guess my question was not formulated correctly. It's more about where best to put the transition decision logic. (that's not totally clear for me yet)

In the synchronous way one would periodically process this logic in a separate thread (if one is in state_x, then check inputs, and then call a transition)
```python
if (machine.state == 'init'):
    # directly read a hardware signal
    while hal.Signal('emcmot.00.enable').get() == 0:
        pass
    machine.go_cart()
```
here `go_cart` is a transition

Another way would be to put this logic in a function and pass this to the on_enter_init callback

```python
def example_function():
    # directly read a hardware signal
    while hal.Signal('emcmot.00.enable').get() == 0:
        pass
    machine.go_cart()

machine.on_enter_init(example_function)
```

One way to find out, and experiment what works best.

**Comment by aleneum** [comment]
I think it really depends on how complex your readout procedure is. It is totally fine to call transitions from within transitions. In that case using `queued=True` as a Machine parameter (see ReadMe) might be useful to prevent weird logs:

```
enter init # enter callback init
exit init # exit callback init
exited init # exit callback init done
enter dest_go_cart # enter callback dest_go_cart
entered dest_go_cart # enter callback dest_go_cart done
entered init # enter callback init done
```

Basically, `queued` will finish the enter callback before the next transition is evaluated and/or executed.  For most cases this should be sufficient.

If you need switch case statements based on states *besides* having a state machine, then something is wrong. I'd suggest to either use specific short living WorkerThreads or -- if you have a readout main loop -- to let the machine set the readout strategy  in `enter`.

**Comment by luminize** [comment]
> If you need switch case statements based on states besides having a state machine, then something is wrong. I'd suggest to either use specific short living WorkerThreads or -- if you have a readout main loop -- to let the machine set the readout strategy in `enter`.

yes, that was my feeling too. Seems like this would be a duplicate.

I'll go and experiment a bit with calling (if need be all) transitions (of which some could be conditional transitions) like machine.go_cart() either periodically, from other states (queued) or from other events.

Thanks for your help.
