### ISSUE TITLE
DepricationWarning when using GraphMachine

### ISSUE THREAD

**Issue by Fawenah** [tyarkoni/transitions#208]
Two issues.

1. GraphMachine generates a Pending DepricationWarning from the imp module

2. Initiating a transition when using the extended machines, in this case GraphMachine, generates a number of PendingDeprecationWarning from a StopIteration.

It is possible (likely) other extended machines that use Diagrams also generate these warnings. I have not tested those so far.

Running in _Python 3.5.2_, latest versions of  `transitions`, `pygraphviz` and `graphviz` from `pip3 install` on `Ubuntu 16.04.2`

1: Warning Messages:
```
/home/<user>/.local/lib/python3.5/site-packages/pygraphviz/graphviz.py:15: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```
1: Minimum Code Example:
```
#!/usr/bin/python3
from transitions.extensions import GraphMachine as Machine
from transitions import State

class Model(object):
    pass
model = Model()
states = [
    State(name='root'),
    State(name='A'),
]
transitions = [
    { 'trigger': 'trigger_1', 'source': 'root', 'dest': 'A' },
]
machine = Machine(
    model=model,
    states=states,
    transitions=transitions,
    initial='root',
)
```

2: Warning Messages:
```
/home/<user>/.local/lib/python3.5/site-packages/pygraphviz/graphviz.py:15: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/<user>/.local/lib/python3.5/site-packages/pygraphviz/agraph.py:734: PendingDeprecationWarning: generator 'AGraph.out_edges_iter' raised StopIteration
  for e in self.out_edges_iter(keys=keys):
/home/<user>/.local/lib/python3.5/site-packages/transitions/extensions/diagrams.py:307: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  for n in graph.nodes_iter():
/home/<user>/.local/lib/python3.5/site-packages/transitions/extensions/diagrams.py:310: PendingDeprecationWarning: generator 'AGraph.subgraphs_iter' raised StopIteration
```
2: Minimum code example:
```
#!/usr/bin/python3
from transitions.extensions import GraphMachine as Machine
from transitions import State

class Model(object):
    pass
model = Model()
states = [
    State(name='root'),
    State(name='A'),
]
transitions = [
    { 'trigger': 'trigger_1', 'source': 'root', 'dest': 'A' },
]
machine = Machine(
    model=model,
    states=states,
    transitions=transitions,
    initial='root',
)
model.trigger_1()
```

**Comment by aleneum** [comment]
Hi @Fawenah,

as you might see, these warnings are generated by `pygraphviz`. The reason why they haven't been shown before is, that transitions just started to use warnings for (pending) deprecations.

* [imp issue](https://github.com/pygraphviz/pygraphviz/blob/master/pygraphviz/graphviz.py#L15)
* the second warning is related to how pygraphviz handles searches [related PEP](https://www.python.org/dev/peps/pep-0479/)

We could silence/filter the warnings but imho the actual addressee of this issue is the dev-team of pygraphviz, isn't it? Silencing might also just a temporal fix because as written in PEP 479, the warnings will become non-silent in Python 3.6.

**Comment by Fawenah** [comment]
I see.
Thanks for the input. I just assumed it was related to `transitions` as I've never had the issue using `pygraphviz` earlier. And it was not an issue when running `transitions` with Python 2.7.

I will either supress them, ignore them or apply a fix for my current repo then.

Kind regards, Fawenah
