### ISSUE TITLE
Transitions tramples logging config

### ISSUE THREAD

**Issue by ulope** [tyarkoni/transitions#21]
With the recently added logging support you added a call to `logging.basicConfig`. That is the WRONG THING(tm) to to do for a library since it destroys the logging config of programs using the library. 

The [logging docs describe how a library should configure logging](https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library)

**Comment by tyarkoni** [comment]
Thanks for the pointer; I removed the basicConfig call.
