### ISSUE TITLE
PyPi Release 0.5.1

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#212]
Hi @tyarkoni,

I just tagged the 0.5.1 release. Could you update the PyPi package?

**Comment by tyarkoni** [comment]
Sure, but it's probably better if I add you as a maintainer on PyPI (for some reason I thought only one person could have push privileges on PyPI, but it looks like I was wrong). What's your PyPI username?

**Comment by aleneum** [comment]
> Sure, but it's probably better if I add you as a maintainer on PyPI 

If thats fine with you, sure.

>  What's your PyPI username?

aleneum

**Comment by tyarkoni** [comment]
Done! Closing.
