### ISSUE TITLE
Inheritance sample

### ISSUE THREAD

**Issue by deubs** [tyarkoni/transitions#22]
In the inheritance sample:
```
class Matter(Machine):
    def say_hello(self): print "hello, new state!"
    def say_goodbye(self): print "goodbye, old state!"

    def __init__(self):
        states = ['solid', 'liquid', 'gas']
        Machine.__init__(self, states, initial='solid')
        self.add_transition('melt', 'solid', 'liquid')
```
constructor args are wrong (1st param is model name). 
It could be like this:
```
Machine.__init__(self, states=states, initial='solid')
```

**Comment by tyarkoni** [comment]
That looks right to me... the inheriting instance is passing itself to the Machine initializer as the first argument in order to set itself as the model. This pattern is currently used in one of the tests and it passes fine, so I'm closing this. But thanks for the close read! :)

**Comment by tyarkoni** [comment]
Sorry @deubs, just realized you were right about this (following #48). My apologies.
