### ISSUE TITLE
set_state equivalent for pushing in events by name?

### ISSUE THREAD

**Issue by bedge** [tyarkoni/transitions#226]
In testing my state thing, I wanted to be able to poke at the state and events.
The state was easy, given the Machine.set_state, but I didn't see an `generate_event...(<event name>` type method.

I settled on
```
        # Funky functools.partial thing as there's no fsm.trigger_event(<event>) method
        eval('fsm.{}'.format(manual_event))()
```
to force a `manual_event` into the mix.

I expect there may be a better way...

**Comment by aleneum** [comment]
Hi @bedge,

are you looking for a way to trigger events by name? If so, `Model.trigger` might be what you are looking for. From the doc:

> Additionally, there is a method called `trigger` now attached to your model. This method lets you execute transitions by name in case dynamic triggering is required.

```python
lump.state
>>> 'gas'
lump.trigger('ionize')
lump.state
>>> 'plasma'
```

**Comment by bedge** [comment]
Ahh, perfect. Must have missed that. thanks!
