### ISSUE TITLE
transitions prevents logging module from working

### ISSUE THREAD

**Issue by bitswype** [tyarkoni/transitions#28]
I admit I am new to logging, but even with this simple example, adding the transitions module prevents logging from working:

```python
import transitions
import logging


if __name__ == '__main__':

    # set up a logger
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                        datefmt='%m-%d %H:%M',
                        filename='mylog.log',
                        filemode='w')

    logging.info("test")
```

if you comment out the ```import transitions``` the logging file is created and "test" shows up as expected.  When the transitions module is imported, the log file is not created.

Am I making the mistake by incorrectly setting up logging?  Or is transitions setting something up for logging that overrides my logging attempts?

**Comment by bitswype** [comment]
I see that a transitions + logging bug was closed 6 days ago.  I installed transitions via pip on 8/1/15.  Do I have an "out of date" version?

**Comment by bitswype** [comment]
I believe this issue can be closed.  I uninstalled the pip version and cloned the git repo for installation and all appears to be working now.

Sorry for the false alarm!

**Comment by tyarkoni** [comment]
Thanks, will close. I'll make an effort to bump version in the next couple of days so that the PyPI version includes this fix.
