### ISSUE TITLE
Allow machine pickle/unpickle

### ISSUE THREAD

**Issue by njouanin** [tyarkoni/transitions#32]
Currently, pickling or unpickling objects with Machine instance fails with TypeError:
example from quick start example:

    import pickle
    print(pickle.dumps(batman))
    TypeError: 'NoneType' object is not callable

This could be useful to be able to save and restore a machine state. I can work on that if you agree.

**Comment by tyarkoni** [comment]
Oh, thanks for catching that. Yes, we definitely want pickling to work properly. I think we probably just needs __getstate__ and __setstate__ methods in the Machine class. If you can add those, that would be much appreciated. Thanks!

**Comment by njouanin** [comment]
I've corrected it. In fact you just need to prevent __getattr__ in core.py from being called with __getstate__. I'll create a push request.
