### ISSUE TITLE
State Callback defined in model class does not run

### ISSUE THREAD

**Issue by zrgravity** [tyarkoni/transitions#38]
I've created a model class that inherits Machine which contains several on_enter_ callbacks for several states (methods defined/named on_enter_stateName(self)). None of the callbacks are executed when the state is entered. In core.py (lines 369-374) it looks like this method of adding callbacks only works if the model class is not "self".

**Comment by tyarkoni** [comment]
Hmm, interesting. @mayowa, do you remember what your rationale was for not allowing model-defined callbacks when the Machine and model are the same object?

**Comment by tyarkoni** [comment]
Ah, I see. The problem is that when the model is self, arguments aren't passed properly from the callback (https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L460). Should be able to fix this, but probably not until the weekend. If anyone else wants to take a crack at a PR, please feel free. :)

**Comment by mayowa** [comment]
@tyarkoni I think that was it, I know that bit of code had me scratching my head a bit, till I figured out what was wrong (Which is why I remember it). Sorry I cant be any clearer. its been been a while since I worked on the project

**Comment by zrgravity** [comment]
I ended up just moving the model to a separate class, as it only required a few lines to be changed (make sure the model isn't inheriting from Machine anymore; that got me for a bit). For me, at least, just updating the documentation to list that condition would be enough.

**Comment by centralniak** [comment]
Would be great to have this working on the `Machine` instance too.

**Comment by tyarkoni** [comment]
Should work now. Let me know if there are any residual issues.
