### ISSUE TITLE
state diagrams

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/transitions#4]
At some point we should add the ability to generate state diagrams via GraphViz or NetworkX.

**Comment by ExpandOcean** [comment]
Agree! I use plantuml, and I think it's better to me:) By the way, your work is just what I want for a long time, thank you!

**Comment by bibi21000** [comment]
Yep ... it should be a good idea. Don't know if you know blockdiag ant its friends (http://blockdiag.com/en/index.html). Maybe the can help you as they can be embeded in many documents (http://blockdiag.com/en/blockdiag/embed_diagram.html)
By the way, thank you very much for transitions ... your statefull machine save hours of dev
Thanks again

**Comment by svdgraaf** [comment]
I actually have code laying around which does just this, rendering the graph using `pygraphviz`, I'm not too satistisfied with the pygraphviz output though:

![asset](https://cloud.githubusercontent.com/assets/19777/11530591/1a0c08a6-98f6-11e5-88a7-756585aafbbb.png)

You can find a quick gist here: https://gist.github.com/svdgraaf/198e2c0cf4cf0a031c84

**Comment by tyarkoni** [comment]
This would be a great start, @svdgraaf! I agree that the result could be improved aesthetically, but for now it would be great to have even rudimentary diagramming capabilities. Do you want to open a PR for this? I suggest putting your code in a separate 'diagrams' module and refactoring slightly so that the graphing call takes a Machine instance as the first argument. We can also maybe add a diagram() method to the Machine class for convenience.

**Comment by svdgraaf** [comment]
Sure, I'll try to make some time this week to create a PR..!

**Comment by svdgraaf** [comment]
I created a PR, let me know of any feedback:
https://github.com/tyarkoni/transitions/pull/47

**Comment by krisztianfekete** [comment]
I like this feature, however I think the current implementation requires `pygraphviz`.
I'd prefer if it would be optional - when the feature is not needed it need not be installed.

**Comment by svdgraaf** [comment]
@krisztianfekete it's optional (you can provide your own diagram class), do you have a suggestion for other tools?

**Comment by tyarkoni** [comment]
Thanks! This is great; will add feedback in the PR conversation. I agree with @krisztianfekete that we probably want to avoid making pygraphviz a hard requirement.

**Comment by tyarkoni** [comment]
Closed in #47. Thanks @svdgraaf! We'll probably want to revisit this and add more features in future, but we can open more specific issues for that.

**Comment by krisztianfekete** [comment]
@svdgraaf I have no suggestion, `pygraphviz` is fine, and I like as it is now - good work! :)
