### ISSUE TITLE
Inheritance sample seems to be incorrect

### ISSUE THREAD

**Issue by TheMysteriousX** [tyarkoni/transitions#48]
This example does not seem work as intended:

```python
>>> from transitions import Machine
>>> class Matter(Machine):
...     def say_hello(self): print ("hello, new state!")
...     def say_goodbye(self): print ("goodbye, old state!")
...     def __init__(self):
...         states = ['solid', 'liquid', 'gas']
...         Machine.__init__(self, states, initial='solid')
...         self.add_transition('melt', 'solid', 'liquid')
...
>>> lump = Matter()
['solid', 'liquid', 'gas']
None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in __init__
  File "/Users/adamb/Developer/transitions-bug/env-osx/lib/python3.5/site-packages/transitions/core.py", line 294, in __init__
    self.set_state(self._initial)
  File "/Users/adamb/Developer/transitions-bug/env-osx/lib/python3.5/site-packages/transitions/core.py", line 325, in set_state
    state = self.get_state(state)
  File "/Users/adamb/Developer/transitions-bug/env-osx/lib/python3.5/site-packages/transitions/core.py", line 319, in get_state
    raise ValueError("State '%s' is not a registered state." % state)
ValueError: State 'solid' is not a registered state.
```

I was going to send a pull, but I'm not sure of the correct behaviour.

The issue is that when invoking Machine.__init__ as a class method, the first parameter from the invocation (self) gets put into the first parameter of Machine.__init__() (self).

This shifts all the parameters left, so states gets put into model etc.

There are three ways to fix this - either add a second self so that Machine.model is set to self:

```python
...         Machine.__init__(self, self, states, initial='solid')
```

or, use an explicit keyword for states so that Machine.model is set to None (this version is used in your test suite):

```python
...         Machine.__init__(self, states=states, initial='solid')
```

This also fixes the example:

```python
...         super(Matter, self).__init__(self, states, initial='solid')
```

Which one is "correct"? When you are using inheritance, is the model intended to be None, or an instance of itself?

**Comment by tyarkoni** [comment]
Thanks for catching that! I think states=states is the way to go, as I'm generally in favor of using keyword args when possible to increase clarity.
