### ISSUE TITLE
PyPI Out of Date despite Version

### ISSUE THREAD

**Issue by wtgee** [tyarkoni/transitions#54]
Hi, the package you have on PyPI is listed as version 0.2.9, which is the latest, but hasn't been updated since 2015-11-10. Turns out those small changes with the `inspect` module on the `add_states` are important when it comes to multiple inheritance. Took me a while to figure out the code was just out of date. Thanks!

**Comment by tyarkoni** [comment]
Sorry, I'll bump version shortly---just waiting on some changes to a big PR before bumping to 0.3. :)

**Comment by wtgee** [comment]
No problem, thanks.  If I'm ambitious in the next week I'll try out the HSM
too.

Cheers,
~Wilfred

On Wed, Dec 30, 2015 at 8:27 AM, Tal Yarkoni <notifications@github.com>
wrote:

> Sorry, I'll bump version shortly---just waiting on some changes to a big
> PR before bumping to 0.3. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyarkoni/transitions/issues/54#issuecomment-168049603>
> .
>



-- 
~Wilfred Tyler Gee

**Comment by tyarkoni** [comment]
Just pushed the new release to PyPI.

**Comment by wtgee** [comment]
Thanks for the note and the update! I was sitting here trying to figure out
why my prod and dev were acting differently, completely forgetting I had
manually updated dev. D'oh.

Updated from `pip` and my robot is able to park itself again. :)

Cheers!

~Wilfred

On Sat, Jan 2, 2016 at 11:49 AM, Tal Yarkoni <notifications@github.com>
wrote:

> Just pushed the new release to PyPI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyarkoni/transitions/issues/54#issuecomment-168430718>
> .
>



-- 
~Wilfred Tyler Gee
