### ISSUE TITLE
on_enter_{state} does not excute automatically

### ISSUE THREAD

**Issue by ExpandOcean** [tyarkoni/transitions#6]
I found on_enter_{state} excute only if I set the on_enter=xxx in defination of state. I think the code below is natural, but it can not work. Do you think it should be supported?

![image](https://cloud.githubusercontent.com/assets/4313075/5751193/0ea08a9e-9c9b-11e4-95f1-0e64072dac24.png)

**Comment by tyarkoni** [comment]
It wouldn't take much work to add that behavior, but I'm not sure how I feel about it. Mainly I worry about feature creep if we start doing things like scanning the data model for already-defined callbacks, etc. It feels a bit inelegant to me to push some of the FSM logic into the data object. That said, I don't feel strongly about it, so let's leave this issue open for now, and if other people weigh in with strong opinions one way or the other, we can re-evaluate.

**Comment by mayowa** [comment]
+1 I think it would a great idea for on_enter_<exit> and on_exit_<state> methods to be detected in the model and executed during transitions, Methinks it would make the code a whole lot more readable

**Comment by tyarkoni** [comment]
Okay, then I'm sold. Does someone want to take a stab at a PR? If not, I should be able to get to it in a few days.

**Comment by mayowa** [comment]
I'll do it and send you a PR

**Comment by tyarkoni** [comment]
Great!
