### ISSUE TITLE
True or False returned upon transition

### ISSUE THREAD

**Issue by hstarmans** [tyarkoni/transitions#64]
As requested in #63, why is `True` returned if this code is executed!? Is this is a bug!?

```python
from transitions import Machine
class Matter(object):
    pass
lump=Matter()
states=['solid', 'liquid']
machine = Machine(model=lump, states=states, initial='solid')
machine.add_transition('melt', source='solid', dest='liquid')
print(lump.melt())  # lump.melt() returns True
```

**Comment by wtgee** [comment]
The documentation doesn't mention the return value but I assume this is intended behavior. You are getting a bool as to whether or not you successfully transitioned or not.

```python
if lump.melt():
    print("Matter melted")
else:
   print("Problem")
```

**Comment by tyarkoni** [comment]
Thanks @hstarmans. Yes, @wtgee is correct: the behavior is fine in this case, the docstring should just say that it returns a boolean indicating whether or not a transition was successfully executed. I'll update the docstring.

**Comment by hstarmans** [comment]
Thanks @tyarkoni  and @wtgee but I don't get it. If functions fail, they should throw exceptions which you can handle. Or stated otherwise, if i have a problem, what should I do !?

**Comment by wtgee** [comment]
@tyarkoni `Transitions.execute` also?

@hstarmans The method isn't failing, the state machine is just not transitioning. I would say if that is a failure to you then throw your own exception:
```python
if not lump.melt():
    raise MyMatterException("Lump would not melt")
```
You would need to write the `MyMatterException` or just raise a regular `Exception`

**Comment by tyarkoni** [comment]
I think 'fail' is ambiguous in this case. When you call a triggering function, it serially executes all individual transitions that start with the current source state, until one successfully executes. A transition may fail to execute because a conditional check returned False. But it's not clear that you want to throw an exception just because all available transitions failed to pass; that would make it impossible to distinguish between a genuine failure in the code and a predictable logical condition that the user may want to handle. So I think the onus is on the user in this case to raise an exception if that's the behavior they want.

**Comment by tyarkoni** [comment]
Thanks @wtgee, added that as well.

**Comment by hstarmans** [comment]
Two things:
_First_, I still believe there is a bug:
 I have made a simple machine, like the one in #63, but without threads etc. which returns `False` although it transitions; see example.
_Secondly_, I would like it not to have `True` or `False` returned or make it optional. There are also other ways to check, so why have it.

```python
from transitions import LockedHierarchicalMachine as Machine
       

class Trafficlight(Machine):
    def __init__(self):
        self.timeoutdic = {'run_green': 3, 'run_red': 5, 'run_yellow': 2}
        states=['paused',{'name':'run', 'children':['green','yellow','red']}]
        transitions = [
                       { 'trigger': 'next', 'source': 'run_green', 'dest': 'run_yellow'},
                       { 'trigger': 'next', 'source': 'run_yellow', 'dest': 'run_red'},
                       { 'trigger': 'next', 'source': 'run_red', 'dest': 'run_green'},
                       {'trigger':'pause','source': 'run', 'dest':'paused'},
                       {'trigger':'pause','source':'paused','dest':'run'},
                       {'trigger':'reset', 'source':'*','dest':'run_green'}
                       ]
        Machine.__init__(self, states=states,transitions=transitions, initial='run_green')
    

trafficlight = Trafficlight()
# returns false
trafficlight.next() 
# returns run_yellow so it did transition,
trafficlight.state  
# returns false
trafficlight.pause() 
# state is paused 
trafficlight.state  
```

**Comment by wtgee** [comment]
Hi @hstarmans,
I ran your example and the results print as True for me. Make sure you are updated to latest as I can't recreate problem.

I don't see a compelling reason to not return the success. What would turning off the success allow you to do that you can't do now?

**Comment by hstarmans** [comment]
@wtgee, I am sorry the bug seems to be in my setup. If I use the terminal with python3 or ipython3 it works fine. If I use; ipython3, pydev and the Eclipse IDE, I get False, strange.

Suppose, I wish to ignore it or not to handle the return value. The only way I can think of it is to use a variable like _ . So _=trafficlight.next() otherwise I end up with all these True or False values in interpreter. I would personally, check whether a state transitioned using the following, or throw an error if a specific condition cannot be met. Anyhow, it is largely aesthetics; I still like transitions in the current situation.
```python 
old=trafficlight.state
trafficlight.next()
if old==trafficlight.state:
   print('do something')
```

**Comment by hstarmans** [comment]
@wtgee, I am sorry the bug seems to be in my setup. If I use the terminal with python3 or ipython3 it works fine. If I use; ipython3, pydev and the Eclipse IDE, I get False, strange.

Suppose, I wish to ignore it or not to handle the return value. The only way I can think of it is to use a variable like _ . So _=trafficlight.next() otherwise I end up with all these True or False values in interpreter. I would personally, check whether a state transitioned using the following, or throw an error if a specific condition cannot be met. Anyhow, it is largely aesthetics; I still like transitions in the current situation.
```python 
old=trafficlight.state
trafficlight.next()
if old==trafficlight.state:
   print('do something')
```
