### ISSUE TITLE
Generic condition method

### ISSUE THREAD

**Issue by stewiegaribaldi** [tyarkoni/transitions#74]
Very good work! I'm curious if I could have a generic condition method where I check the transition source and dest field and return True/False accordingly. I can't seem to find transition's dest from  generic condition method. Or may be there's a better way?

**Comment by tyarkoni** [comment]
Not sure I follow... Can you explain what you're trying to do? A code sample might help as well.

**Comment by stewiegaribaldi** [comment]
I have this:

transitions = [
    { 'trigger': 'pulse', 'source': 'input', 'dest': 'input', 'conditions': 'IsConditionMet'},
    { 'trigger': 'pulse', 'source': 'input', 'dest': 'log', 'conditions': 'IsConditionMet'},
    { 'trigger': 'pulse', 'source': 'input', 'dest': 'display', 'conditions': 'IsConditionMet'},
    { 'trigger': 'reset', 'source': '*', 'dest': 'input'}
]

As you can see all the conditions are the same i.e. IsConditionMet
Then I have:

def IsConditionMet(self):
  	if self.State == 'input' and dest == 'input':
		return False
	.....
	return False

The idea is I don't want to populate my class with each condition in transition.
I just want to have 1 method.

Please let me know if that make sense. I may be having paralysis analysis =)

**Comment by tyarkoni** [comment]
Oh, I see. It should actually work exactly the way you want it to, I believe. In your example, 'IsConditionMet' is just a pointer to the function. It's fine if all conditions point to the same function. All you're missing is catching the EventData instance. I.e., this should work:

```python
def IsConditionMet(self, event_data):
    # trans is a Transition instance that has .source and .dest properties you can access.
    trans = event_data.transition
    ...
    return False
```

Closing this unless there are any other issues.

**Comment by stewiegaribaldi** [comment]
Wow! You are absolutely correct! Thank you for your prompt reply and solution! Awesome module!!!!!
