### ISSUE TITLE
Define transitions on states rather than machine?

### ISSUE THREAD

**Issue by bennyrowland** [tyarkoni/transitions#81]
Would it be possible to change the way transitions are added (or add an additional method for adding them) so that they are added to the source state rather than to the machine? It seems to me that something like:
machine['solid'].add_transition('sublimate', 'gas')
is more immediately comprehensible than:
machine.add_transition('sublimate', 'solid', 'gas')
as it allows the transitions to be conceptually grouped around the source state. I suspect that the wildcard might cause some implementation difficulties, but are there any other issues with this kind of syntax?

**Comment by tyarkoni** [comment]
In theory we _could_ implement something like this, as we don't currently use the `__getitem__` accessor on the Machine for anything. But it would be a bit clunky, as we'd probably need to create a new class that wraps Event, or something like that.

That said, I don't think we really want to go down this road... Personally, I don't like the idea of having a bunch of different ways to achieve the same goal, and it's not clear to me that we would want machine[] to index into States--one could, e.g., imagine indexing directly into Transitions, or Events, etc. Plus maintaining multiple interfaces would start to defeat the point of keeping the core lib as simple as possible. So unless @wtgee and @aleneum are strongly in favor, I would vote to close this--though I do appreciate you bringing it up, @bennyrowland, as it's an interesting idea.

**Comment by aleneum** [comment]
yeah, the idea is interesting but I do agree with @tyarkoni. If the code is not comprehensible enough one may fall back to
```python
machine.add_transition(trigger='sublimate', source='solid', dest='gas')
```

**Comment by aleneum** [comment]
Hi @tyarkoni,

sorry for reopening this but I just realised

```python
machine.add_transition(trigger='sublimate', source='solid', dest='gas')
```

is not possible since arguments 1 to 3 have no keyword. Do you think this is desirable in cases where add_transition('sublimate', 'solid', 'gas') is not verbose enough?

**Comment by aleneum** [comment]
gnaaah, nevermind. it does work m(.
