### ISSUE TITLE
Improve nested extension

### ISSUE THREAD

**Issue by aleneum** [tyarkoni/transitions#86]
Since my first implementation I got some feedback about the way I have done Hierarchical State Machines in transitions. The current implementation has some issues:
* **underscore separator does not cut it**: We have been aware of the fact, that underscore is no perfect solution but it allowed nested states to reuse many of transitions' core functionality (auto transitions and callback addition). However, since underscore can also be used in state naming, there is no way to tell if `stateC_alt_state1` is actually a (two times) nested state or not. Even worse could be a situation where the naming of states collide (`stateC` + `alt_state1`; `stateC_alt` + `state_1`). I haven't even tried what the ambiguity in auto transition would do but `to_stateC_alt_state1` would probably do random things.
* **flatten strategy destroys hierarchical information**: After flattening, retrieving hierarchical information, especially related to transitions, is bothersome. You cannot rely on the name. This means you have to retrieve the state in question and have a look at the parent (and its parent and so on) to actually know HOW nested the state was. I still think flattening is not a bad approach but especially in combination with the underscore separator it makes things unnecessarily complicated. The blueprint strategy could compensate this a bit and made copying possible but its one of the things that is hard to comprehend and maintain especially if the 'causer' is not available anymore.

I spent some time thinking about it and came to the conclusion that I have to change some things under the hood but also violate the first law of a library developer which is *'One shall not break the API'* by **switching from underscore to a dot separator**. Why choosing the dot:

* It's already implicitly forbidden in naming because it makes the convenience features of transitions useless: `'my.state' -> to_my.state (Nope) -> on_enter_my.state (Nope)`
* From python's point of view it's suitable to imply nesting: `machine.to_stateA.alt.state1` resembles common `object.child.property` nesting. I have chosen `to_stateC.alt` rather than `to.stateC.alt` to stick to the way transition's core work. This is done with a callable [FunctionWrapper](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855R11) which contains auto transitions to child states as properties (wrapping happens [here](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855R231)).

Setback: The way of returning callbacks with `partial` is not that easy to extend to allow `on_enter_C.alt('callback')`. The best I came up with was `on_enter_C().alt('callback')` without overwriting `__attr__` in `nested` (which I try to avoid). So I have chosen another way which is `on_enter/on_exit('C.alt','callback')`. Implicit calling of model functions does not work in this case though.

However, the rework brings new features which hopefully make up for it:
* **hierarchical order is kept**: No need for [blueprints](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855L159) anymore
* **Machines can be embedded and not just copied into another Machine**: `{name:'stateC', children:another_machine}` no longer copies the structure but [references](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855R179) the states directly. This allows to keep the states of a machine and dynamical add them to another super state machine. This becomes handy if you subclass States to keep certain informations independently of their current status or if creating a state requires much time and/or resources.
* **Embedding machines allows siblings**: `{name:'stateC', children:['1',another_machine]}`is no longer prohibited. If `another_machine` also contains a state named `1` a [ValueError](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855R207) is raised.
* **Hierarchical delegation of transitions**:  Previously, parent state transitions had to be copied to its children. Having a transition from `stateC` means 3 transitions for 3 children and 12 if these children also contain 3 children. Additionally, it makes the trigger unusable for children or leads to unpredictable behaviour if substates 'accidentally' use the same trigger. In this case addition order decides which transition is executed. *Not anymore!* After the rework trigger events are [delegated](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-0340de4ea0a66c6a0af24ea2b01ea855R102) from children to parents. This means children can intentionally overwrite their parents behaviour.  

Ah yeah, I also [merged](https://github.com/tyarkoni/transitions/compare/dev-nested#diff-e29d8b8e9d103e0a5c6a8746a56a0f0cL59) `AAGraph` and `AGraph` since `AAGraph` was already the default class chosen and I haven't found any occasion where `AGraph` was explicitly used. Actually this is also the reason why #85 fails the coverage test I guess. `AGraph._add_nodes` and `AGraph._add_edges` aren't used during testing.

There is still some work to be done (tweaking, documentation and merging the latest changes for instance), that's why I haven't opened a pull request yet. But it has progressed enough to gather some feedback.

So what are your thoughts about that? Is `to_stateC.alt.stateD()` and `on_enter('stateC.alt.stateC','callback')` sufficient? Is it okay to break the API and use dots from now on?

**Comment by wtgee** [comment]
Hi @aleneum, sorry it was so long getting back to you on this.

First, I don't like the dot notation at all. Second, it probably makes most sense so I'm not really opposed. I just don't like it. :) I do think the features it provides in this implementation far outweigh the disadvantages although I am also a little concerned about breaking the API. I especially think the actual embedding (vs flattening) moves them toward a true hierarchical SM, which is a lot better.

I am a little confused by your examples `to_stateC.alt.stateD()` and `on_enter('stateC.alt.stateD','callback') `. Is `alt` the name of the nested FSM? It seems like you are saying `stateD` belongs to `alt` which belongs to `stateC`, is that correct?

**Comment by tyarkoni** [comment]
I'm okay with breaking the API in this case. I mean, I don't think we should make a habit of it, but I suspect the number of people currently using the HSM extension is not very large yet, so, better to break it now rather than later. :) But we should probably mention this change in a parenthetical comment in the docs though (at least for a few months).

Otherwise this all sounds good to me. I agree that if we can avoid flattening, that would be better. I also think the `on_enter/on_exit('C.alt','callback')` approach is a good solution.

**Comment by aleneum** [comment]
> Is alt the name of the nested FSM? It seems like you are saying stateD belongs to alt which belongs to stateC, is that correct?

Yes. `stateC` has children states and one of them is `alt`. This state also has children and one of them is `stateD`. `stateD` might have children, too. I updated my first post to use `state1` instead of `stateD`. It's already confusing enough without me mixing up namespaces of nested states.

> I just don't like it. :)

haha, fair enough. The separator is now a class variable which means theoretically you could use any string you like. I opted for '.' because of chaining reasons but adding a method like a generic `go_to` like `model.go_to('stateC<42>alt<42>state1')` is not that hard to implement. Or you could play with fire like `model.go_to('stateC➳alt➳state1')` ;).

> better to break it now rather than later. :)

I could add a `fallback`. If `NestedState.separator=='_'` then leave out FunctionWrappers. In this case the behaviour would not change. I could even make `NestedState.separator='_'` the default value for the first time and add a deprecation warning.

>  But we should probably mention this change in a parenthetical comment in the docs though (at least for a few months).

Yeah, about that... Most changes done in the bigger refactoring during the graph rework have not been documented yet. For instance the factory and mixing model or how graphs work now. I will give it a first shot and would be glad if you could review it then.

**Comment by wtgee** [comment]
On Tue, Mar 8, 2016 at 11:58 PM, Alexander Neumann <notifications@github.com
> wrote:

> Is alt the name of the nested FSM? It seems like you are saying stateD
> belongs to alt which belongs to stateC, is that correct?
>
> Yes. stateC has children states and one of them is alt. This state also
> has children and one of them is stateD. stateD might have children, too.
> I updated my first post to use state1 instead of stateD. It's already
> confusing enough without me mixing up namespaces of nested states.
>
> I just don't like it. :)
>
> haha, fair enough. The separator is now a class variable which means
> theoretically you could use any string you like. I opted for '.' because of
> chaining reasons but adding a method like a generic go_to like
> model.go_to('stateC<42>alt<42>state1') is not that hard to implement. Or
> you could play with fire like model.go_to('stateC➳alt➳state1') ;).
>

Fun. I keep telling myself I'm going to map out some cool utf8 symbols for
easy typing, maybe now's the time! :)


> better to break it now rather than later. :)
>
> I could add a fallback. If NestedState.separator=='_' then leave out
> FunctionWrappers. In this case the behaviour would not change. I could even
> make NestedState.separator='_' the default value for the first time and
> add a deprecation warning.
>
I like this idea. Certainly we need to give at least one release cycle of
warning if not more. Speaking of which...


> But we should probably mention this change in a parenthetical comment in
> the docs though (at least for a few months).
>
> Yeah, about that... Most changes done in the bigger refactoring during the
> graph rework have not been documented yet. For instance the factory and
> mixing model or how graphs work now. I will give it a first shot and would
> be glad if you could review it then.
>
Yes, I can help try to make a push to get things updated and get a new
release out.

I think this enhancement should try to make it in that release.



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyarkoni/transitions/issues/86#issuecomment-194216895>
> .
>



-- 
~Wilfred Tyler Gee

**Comment by aleneum** [comment]
Hi,

just a small update: I hadn't had time to work on it during the last month. But I will push some changes this week for sure!

best regards,
alex

**Comment by aleneum** [comment]
I rearranged and extended the documentation and added the custom separator as a feature which is disabled by default (underscore is used). The documentation changes are limited to the 'Extensions' chapter. Feel free to reword phrases or ask for clarification if something is unclear. 

@wtgee, @tyarkoni: Do you think unicode separators for python 2 is a must have? I tried to 'fix' unicode handling in transitions but I feel like this will break for someone somewhere for sure. If the terminal/command prompt cannot handle unicode right for instance. It does work for python 3 without any hassle though.

```python
  File "/[...]/transitions/transitions/core.py", line 395, in add_states
    partial(self.is_state, state.name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u21a6' in position 4: ordinal not in range(128)
```

**Comment by aleneum** [comment]
renamed `dev-nested` to `dev-0.4`

**Comment by tyarkoni** [comment]
I don't think we need to support unicode separators in 2--I agree it will probably create more trouble than it solves.

**Comment by aleneum** [comment]
branch has been merged into master and unicode separator support for python2 is a 'wontfix' for now
