### ISSUE TITLE
Logger as parameter to use with multiple machines

### ISSUE THREAD

**Issue by khigia** [tyarkoni/transitions#89]
Use of standard logging is great. However there are use cases where more than one FSM can be instanciated, in which case it is difficult to match log lines with code logic.

I would like to propose an optional logger parameter when instanciating the machine (with default to current global logger). This way user has possibility to pass a logger instance embedding some context and configuration.

**Comment by wtgee** [comment]
Seems like you could just pass some kind of `name` or `id` attribute of the FSM to the logger rather than passing multiple loggers around. 

I'm not entirely sure this is something that most users would need and that we would want to incorporate but will wait for other opinions.

**Comment by khigia** [comment]
IMHO using name or id is not easier; passing a logger allow user to embed any context (using LoggerAdapter) without having FSM code to have more data (name or id); and logger has advantage of having its own logging conf (level etc). It's completely transparent and optional.

Btw, if this feature is seen as useful (or at least not creating issue I haven't foreseen), I can maybe propose a pull request (to be honest I haven't looked at all extensions code though).

And one last question: is creating issue a good way to propose feature? let me know and I will use the project standard workflow!

Thanks you very much.

**Comment by tyarkoni** [comment]
I think I'd be okay adding an optional logger argument to the Machine constructor. It seems like a pretty minimal change, and I can see a use case for it. If you want to submit a PR, that would be great.

And yes, feature requests should go here.

**Comment by khigia** [comment]
Pull request created: https://github.com/tyarkoni/transitions/pull/91

**Comment by khigia** [comment]
Hum, in core, having a logger as attribute is nice. But in extensions (because of deepcopy and pickle use) the code is a bit convoluted. Maybe better to close the pull request and add a name attribute to Machine as @wtgee proposed. Let me know.

**Comment by aleneum** [comment]
I guess your implementation is pretty close to the minimal changes necessary to make this work.
So `__setstate__`, `__getstate__` and `_deepcopy_` have to be written and/or altered. This is quite some overhead imho. However, deepcopy should not be necessary any longer if `dev-nested` gets merged.  Being able to deep copy machines is nice though if you ask me.
Concerning this I favour the 'machine id/name' solution and -- optionally --  extending the logging string a bit.

**Comment by aleneum** [comment]
I have added an identifier string to Machine in `dev-0.4`.

machine(initial='A', name='Test Machine') results in:
machine.to_B()
machine.to_C()
```
-------------------- >> begin captured logging << --------------------
transitions.core: INFO: Test Machine: Initiating transition from state A to state B...
transitions.core: INFO: Test Machine: Exited state A
transitions.core: INFO: Test Machine: Entered state B
transitions.core: INFO: Test Machine: Initiating transition from state B to state C...
transitions.core: INFO: Test Machine: Exited state B
transitions.core: INFO: Test Machine: Entered state C
--------------------- >> end captured logging << ---------------------
```
