### ISSUE TITLE
Support initial transition?

### ISSUE THREAD

**Issue by ExpandOcean** [tyarkoni/transitions#9]
I found there is no initial transition supported yet, that means the "on_enter_initial" will not excute when state machine start to run to the initial state at the first time. Do you think it's necessary? 
UML state machine supports that.(http://en.wikipedia.org/wiki/UML_state_machine)
![image](https://cloud.githubusercontent.com/assets/4313075/5759622/ff7da898-9d09-11e4-8acb-4d1d414c2707.png)

**Comment by tyarkoni** [comment]
Hmm... I can see the benefit of that in some cases, but I don't think it's worth adding here. One reason to keep it the way it is is that we currently allow Machines to be initialized without an explicit initial state, in which case a placeholder 'initial' state is created. In a sense, I think of that placeholder as a kind of null state that the user has to move out of before anything meaningful happens. So for now I guess I'd prefer to leave it as is. Am closing the issue, but will re-open if there's additional demand for this.
