### ISSUE TITLE
Rename MachineGraphSupport?

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/transitions#98]
The new mixin architecture is great (as is the associated table in the README), but is there a reason MachineGraphSupport doesn't follow the rest of the nomenclature? It seems like it should be called GraphMachine for consistency. Any objections to renaming this class?

**Comment by aleneum** [comment]
If I am not mistaken, @wtgee has chosen this name because the first version did not inherit from Machine (but I am not 100% sure). But since it does now, naming it GraphMachine sounds good to me.

**Comment by wtgee** [comment]
:+1:
